# Configuration generated by "gen/generator.go"; DO NOT EDIT.
# In order to regenerate this file execute `go generate` from the repository root.
# More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/main/README.md).

resource "aci_dscp_to_priority_map" "example_custom_qos_policy" {
  parent_dn = aci_custom_qos_policy.example.id
  from      = "AF11"
  to        = "AF22"
}
