// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FhsRaGuardPolModel struct {
	Annotation         types.String `tfsdk:"annotation"`
	Descr              types.String `tfsdk:"description"`
	ManagedConfigCheck types.String `tfsdk:"managed_config_check"`
	ManagedConfigFlag  types.String `tfsdk:"managed_config_flag"`
	MaxHopLimit        types.String `tfsdk:"max_hop_limit"`
	MaxRouterPref      types.String `tfsdk:"max_router_preference"`
	MinHopLimit        types.String `tfsdk:"min_hop_limit"`
	Name               types.String `tfsdk:"name"`
	NameAlias          types.String `tfsdk:"name_alias"`
	OtherConfigCheck   types.String `tfsdk:"other_config_check"`
	OtherConfigFlag    types.String `tfsdk:"other_config_flag"`
	OwnerKey           types.String `tfsdk:"owner_key"`
	OwnerTag           types.String `tfsdk:"owner_tag"`
	TagAnnotation      types.Set    `tfsdk:"annotations"`
	TagTag             types.Set    `tfsdk:"tags"`
}

func FhsRaGuardPolModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"annotation":            types.StringType,
		"description":           types.StringType,
		"managed_config_check":  types.StringType,
		"managed_config_flag":   types.StringType,
		"max_hop_limit":         types.StringType,
		"max_router_preference": types.StringType,
		"min_hop_limit":         types.StringType,
		"name":                  types.StringType,
		"name_alias":            types.StringType,
		"other_config_check":    types.StringType,
		"other_config_flag":     types.StringType,
		"owner_key":             types.StringType,
		"owner_tag":             types.StringType,
		"annotations": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: TagAnnotationModelAttributeTypes(),
			},
		},
		"tags": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: TagTagModelAttributeTypes(),
			},
		},
	}
}

func NewFhsRaGuardPolModelNull() FhsRaGuardPolModel {
	return FhsRaGuardPolModel{
		Annotation:         types.StringNull(),
		Descr:              types.StringNull(),
		ManagedConfigCheck: types.StringNull(),
		ManagedConfigFlag:  types.StringNull(),
		MaxHopLimit:        types.StringNull(),
		MaxRouterPref:      types.StringNull(),
		MinHopLimit:        types.StringNull(),
		Name:               types.StringNull(),
		NameAlias:          types.StringNull(),
		OtherConfigCheck:   types.StringNull(),
		OtherConfigFlag:    types.StringNull(),
		OwnerKey:           types.StringNull(),
		OwnerTag:           types.StringNull(),
		TagAnnotation: types.SetNull(
			types.ObjectType{
				AttrTypes: TagAnnotationModelAttributeTypes(),
			},
		),
		TagTag: types.SetNull(
			types.ObjectType{
				AttrTypes: TagTagModelAttributeTypes(),
			},
		),
	}
}

func (m *FhsRaGuardPolModel) BuildRN() string {
	return "raguardpol"
}

func (m *FhsRaGuardPolModel) BuildDN(parentDN string) string {
	return parentDN + "/" + m.BuildRN()
}

func (m *FhsRaGuardPolModel) BuildPayloadObject(
	ctx context.Context,
	priorState *FhsRaGuardPolModel,
	nested bool,
	defaultAnnotation string,
) (map[string]any, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	attributes := map[string]any{}
	children := make([]map[string]any, 0)
	if !m.Annotation.IsNull() && !m.Annotation.IsUnknown() {
		attributes["annotation"] = m.Annotation.ValueString()
	} else if nested {
		attributes["annotation"] = defaultAnnotation
	}
	if !m.Descr.IsNull() && !m.Descr.IsUnknown() {
		attributes["descr"] = m.Descr.ValueString()
	}
	if !m.ManagedConfigCheck.IsNull() && !m.ManagedConfigCheck.IsUnknown() {
		attributes["managedConfigCheck"] = m.ManagedConfigCheck.ValueString()
	}
	if !m.ManagedConfigFlag.IsNull() && !m.ManagedConfigFlag.IsUnknown() {
		attributes["managedConfigFlag"] = m.ManagedConfigFlag.ValueString()
	}
	if !m.MaxHopLimit.IsNull() && !m.MaxHopLimit.IsUnknown() {
		attributes["maxHopLimit"] = m.MaxHopLimit.ValueString()
	}
	if !m.MaxRouterPref.IsNull() && !m.MaxRouterPref.IsUnknown() {
		attributes["maxRouterPref"] = m.MaxRouterPref.ValueString()
	}
	if !m.MinHopLimit.IsNull() && !m.MinHopLimit.IsUnknown() {
		attributes["minHopLimit"] = m.MinHopLimit.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		attributes["name"] = m.Name.ValueString()
	}
	if !m.NameAlias.IsNull() && !m.NameAlias.IsUnknown() {
		attributes["nameAlias"] = m.NameAlias.ValueString()
	}
	if !m.OtherConfigCheck.IsNull() && !m.OtherConfigCheck.IsUnknown() {
		attributes["otherConfigCheck"] = m.OtherConfigCheck.ValueString()
	}
	if !m.OtherConfigFlag.IsNull() && !m.OtherConfigFlag.IsUnknown() {
		attributes["otherConfigFlag"] = m.OtherConfigFlag.ValueString()
	}
	if !m.OwnerKey.IsNull() && !m.OwnerKey.IsUnknown() {
		attributes["ownerKey"] = m.OwnerKey.ValueString()
	}
	if !m.OwnerTag.IsNull() && !m.OwnerTag.IsUnknown() {
		attributes["ownerTag"] = m.OwnerTag.ValueString()
	}
	if !m.TagAnnotation.IsNull() && !m.TagAnnotation.IsUnknown() {
		var desiredChildren []TagAnnotationModel
		diagnostics.Append(m.TagAnnotation.ElementsAs(ctx, &desiredChildren, false)...)
		if diagnostics.HasError() {
			return nil, diagnostics
		}

		var priorChildren []TagAnnotationModel
		if priorState != nil &&
			!priorState.TagAnnotation.IsNull() &&
			!priorState.TagAnnotation.IsUnknown() {
			diagnostics.Append(priorState.TagAnnotation.ElementsAs(ctx, &priorChildren, false)...)
			if diagnostics.HasError() {
				return nil, diagnostics
			}
		}

		for desiredIndex := range desiredChildren {
			desiredChild := &desiredChildren[desiredIndex]
			var priorChild *TagAnnotationModel
			for priorIndex := range priorChildren {
				if priorChildren[priorIndex].BuildRN() == desiredChild.BuildRN() {
					priorChild = &priorChildren[priorIndex]
					break
				}
			}

			childObject, childDiagnostics := desiredChild.BuildPayloadObject(ctx, priorChild, true, defaultAnnotation)
			diagnostics.Append(childDiagnostics...)
			if diagnostics.HasError() {
				return nil, diagnostics
			}
			children = append(children, map[string]any{"tagAnnotation": childObject})
		}

		for priorIndex := range priorChildren {
			priorChild := &priorChildren[priorIndex]
			found := false
			for desiredIndex := range desiredChildren {
				if desiredChildren[desiredIndex].BuildRN() == priorChild.BuildRN() {
					found = true
					break
				}
			}
			if found {
				continue
			}
			children = append(children, map[string]any{"tagAnnotation": priorChild.BuildNestedDeletePayloadObject()})
		}
	}
	if !m.TagTag.IsNull() && !m.TagTag.IsUnknown() {
		var desiredChildren []TagTagModel
		diagnostics.Append(m.TagTag.ElementsAs(ctx, &desiredChildren, false)...)
		if diagnostics.HasError() {
			return nil, diagnostics
		}

		var priorChildren []TagTagModel
		if priorState != nil &&
			!priorState.TagTag.IsNull() &&
			!priorState.TagTag.IsUnknown() {
			diagnostics.Append(priorState.TagTag.ElementsAs(ctx, &priorChildren, false)...)
			if diagnostics.HasError() {
				return nil, diagnostics
			}
		}

		for desiredIndex := range desiredChildren {
			desiredChild := &desiredChildren[desiredIndex]
			var priorChild *TagTagModel
			for priorIndex := range priorChildren {
				if priorChildren[priorIndex].BuildRN() == desiredChild.BuildRN() {
					priorChild = &priorChildren[priorIndex]
					break
				}
			}

			childObject, childDiagnostics := desiredChild.BuildPayloadObject(ctx, priorChild, true, defaultAnnotation)
			diagnostics.Append(childDiagnostics...)
			if diagnostics.HasError() {
				return nil, diagnostics
			}
			children = append(children, map[string]any{"tagTag": childObject})
		}

		for priorIndex := range priorChildren {
			priorChild := &priorChildren[priorIndex]
			found := false
			for desiredIndex := range desiredChildren {
				if desiredChildren[desiredIndex].BuildRN() == priorChild.BuildRN() {
					found = true
					break
				}
			}
			if found {
				continue
			}
			children = append(children, map[string]any{"tagTag": priorChild.BuildNestedDeletePayloadObject()})
		}
	}

	payloadObject := map[string]any{"attributes": attributes}
	payloadObject["children"] = children
	return payloadObject, diagnostics
}

func (m *FhsRaGuardPolModel) BuildNestedDeletePayloadObject() map[string]any {
	attributes := map[string]any{"status": "deleted"}
	return map[string]any{
		"attributes": attributes,
		"children":   []map[string]any{},
	}
}
