// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/main/README.md).

package models

import (
	"context"
	"strings"

	"github.com/ciscoecosystem/aci-go-client/v2/container"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	customTypes "github.com/CiscoDevNet/terraform-provider-aci/v2/internal/custom_types"
	modelHelpers "github.com/CiscoDevNet/terraform-provider-aci/v2/internal/provider/models/helpers"
)

type FvAEPgModel struct {
	Annotation       types.String                      `tfsdk:"annotation"`
	Descr            types.String                      `tfsdk:"description"`
	ExceptionTag     types.String                      `tfsdk:"contract_exception_tag"`
	FloodOnEncap     types.String                      `tfsdk:"flood_in_encapsulation"`
	FwdCtrl          types.String                      `tfsdk:"forwarding_control"`
	HasMcastSource   types.String                      `tfsdk:"has_multicast_source"`
	IsAttrBasedEPg   types.String                      `tfsdk:"useg_epg"`
	MatchT           types.String                      `tfsdk:"match_criteria"`
	Name             types.String                      `tfsdk:"name"`
	NameAlias        types.String                      `tfsdk:"name_alias"`
	PcEnfPref        types.String                      `tfsdk:"intra_epg_isolation"`
	PcTag            types.String                      `tfsdk:"pc_tag"`
	PrefGrMemb       types.String                      `tfsdk:"preferred_group_member"`
	Prio             customTypes.FvAEPgPrioStringValue `tfsdk:"priority"`
	Scope            types.String                      `tfsdk:"scope"`
	Shutdown         types.String                      `tfsdk:"admin_state"`
	FvCrtrn          types.Object                      `tfsdk:"epg_useg_block_statement"`
	FvRsAEPgMonPol   types.Object                      `tfsdk:"relation_to_monitoring_policy"`
	FvRsAepAtt       types.Set                         `tfsdk:"relation_to_attachable_access_entity_profiles"`
	FvRsBd           types.Object                      `tfsdk:"relation_to_bridge_domain"`
	FvRsCons         types.Set                         `tfsdk:"relation_to_consumed_contracts"`
	FvRsConsIf       types.Set                         `tfsdk:"relation_to_imported_contracts"`
	FvRsCustQosPol   types.Object                      `tfsdk:"relation_to_custom_qos_policy"`
	FvRsDomAtt       types.Set                         `tfsdk:"relation_to_domains"`
	FvRsDppPol       types.Object                      `tfsdk:"relation_to_data_plane_policing_policy"`
	FvRsFcPathAtt    types.Set                         `tfsdk:"relation_to_fibre_channel_paths"`
	FvRsIntraEpg     types.Set                         `tfsdk:"relation_to_intra_epg_contracts"`
	FvRsNodeAtt      types.Set                         `tfsdk:"relation_to_static_leafs"`
	FvRsPathAtt      types.Set                         `tfsdk:"relation_to_static_paths"`
	FvRsProtBy       types.Set                         `tfsdk:"relation_to_taboo_contracts"`
	FvRsProv         types.Set                         `tfsdk:"relation_to_provided_contracts"`
	FvRsSecInherited types.Set                         `tfsdk:"relation_to_contract_masters"`
	FvRsTrustCtrl    types.Object                      `tfsdk:"relation_to_trust_control_policy"`
	TagAnnotation    types.Set                         `tfsdk:"annotations"`
	TagTag           types.Set                         `tfsdk:"tags"`
}

func FvAEPgModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"annotation":             types.StringType,
		"description":            types.StringType,
		"contract_exception_tag": types.StringType,
		"flood_in_encapsulation": types.StringType,
		"forwarding_control":     types.StringType,
		"has_multicast_source":   types.StringType,
		"useg_epg":               types.StringType,
		"match_criteria":         types.StringType,
		"name":                   types.StringType,
		"name_alias":             types.StringType,
		"intra_epg_isolation":    types.StringType,
		"pc_tag":                 types.StringType,
		"preferred_group_member": types.StringType,
		"priority":               customTypes.FvAEPgPrioStringType{},
		"scope":                  types.StringType,
		"admin_state":            types.StringType,
		"epg_useg_block_statement": types.ObjectType{
			AttrTypes: FvCrtrnModelAttributeTypes(),
		},
		"relation_to_monitoring_policy": types.ObjectType{
			AttrTypes: FvRsAEPgMonPolModelAttributeTypes(),
		},
		"relation_to_attachable_access_entity_profiles": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsAepAttModelAttributeTypes(),
			},
		},
		"relation_to_bridge_domain": types.ObjectType{
			AttrTypes: FvRsBdModelAttributeTypes(),
		},
		"relation_to_consumed_contracts": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsConsModelAttributeTypes(),
			},
		},
		"relation_to_imported_contracts": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsConsIfModelAttributeTypes(),
			},
		},
		"relation_to_custom_qos_policy": types.ObjectType{
			AttrTypes: FvRsCustQosPolModelAttributeTypes(),
		},
		"relation_to_domains": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsDomAttModelAttributeTypes(),
			},
		},
		"relation_to_data_plane_policing_policy": types.ObjectType{
			AttrTypes: FvRsDppPolModelAttributeTypes(),
		},
		"relation_to_fibre_channel_paths": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsFcPathAttModelAttributeTypes(),
			},
		},
		"relation_to_intra_epg_contracts": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsIntraEpgModelAttributeTypes(),
			},
		},
		"relation_to_static_leafs": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsNodeAttModelAttributeTypes(),
			},
		},
		"relation_to_static_paths": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsPathAttModelAttributeTypes(),
			},
		},
		"relation_to_taboo_contracts": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsProtByModelAttributeTypes(),
			},
		},
		"relation_to_provided_contracts": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsProvModelAttributeTypes(),
			},
		},
		"relation_to_contract_masters": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: FvRsSecInheritedModelAttributeTypes(),
			},
		},
		"relation_to_trust_control_policy": types.ObjectType{
			AttrTypes: FvRsTrustCtrlModelAttributeTypes(),
		},
		"annotations": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: TagAnnotationModelAttributeTypes(),
			},
		},
		"tags": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: TagTagModelAttributeTypes(),
			},
		},
	}
}

func NewFvAEPgModelNull() FvAEPgModel {
	return FvAEPgModel{
		Annotation:     types.StringNull(),
		Descr:          types.StringNull(),
		ExceptionTag:   types.StringNull(),
		FloodOnEncap:   types.StringNull(),
		FwdCtrl:        types.StringNull(),
		HasMcastSource: types.StringNull(),
		IsAttrBasedEPg: types.StringNull(),
		MatchT:         types.StringNull(),
		Name:           types.StringNull(),
		NameAlias:      types.StringNull(),
		PcEnfPref:      types.StringNull(),
		PcTag:          types.StringNull(),
		PrefGrMemb:     types.StringNull(),
		Prio:           customTypes.NewFvAEPgPrioStringNull(),
		Scope:          types.StringNull(),
		Shutdown:       types.StringNull(),
		FvCrtrn:        types.ObjectNull(FvCrtrnModelAttributeTypes()),
		FvRsAEPgMonPol: types.ObjectNull(FvRsAEPgMonPolModelAttributeTypes()),
		FvRsAepAtt: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsAepAttModelAttributeTypes(),
			},
		),
		FvRsBd: types.ObjectNull(FvRsBdModelAttributeTypes()),
		FvRsCons: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsConsModelAttributeTypes(),
			},
		),
		FvRsConsIf: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsConsIfModelAttributeTypes(),
			},
		),
		FvRsCustQosPol: types.ObjectNull(FvRsCustQosPolModelAttributeTypes()),
		FvRsDomAtt: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsDomAttModelAttributeTypes(),
			},
		),
		FvRsDppPol: types.ObjectNull(FvRsDppPolModelAttributeTypes()),
		FvRsFcPathAtt: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsFcPathAttModelAttributeTypes(),
			},
		),
		FvRsIntraEpg: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsIntraEpgModelAttributeTypes(),
			},
		),
		FvRsNodeAtt: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsNodeAttModelAttributeTypes(),
			},
		),
		FvRsPathAtt: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsPathAttModelAttributeTypes(),
			},
		),
		FvRsProtBy: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsProtByModelAttributeTypes(),
			},
		),
		FvRsProv: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsProvModelAttributeTypes(),
			},
		),
		FvRsSecInherited: types.SetNull(
			types.ObjectType{
				AttrTypes: FvRsSecInheritedModelAttributeTypes(),
			},
		),
		FvRsTrustCtrl: types.ObjectNull(FvRsTrustCtrlModelAttributeTypes()),
		TagAnnotation: types.SetNull(
			types.ObjectType{
				AttrTypes: TagAnnotationModelAttributeTypes(),
			},
		),
		TagTag: types.SetNull(
			types.ObjectType{
				AttrTypes: TagTagModelAttributeTypes(),
			},
		),
	}
}

func (m *FvAEPgModel) BuildRN() string {
	rn := "epg-{name}"
	rn = strings.ReplaceAll(rn, "{name}", m.Name.ValueString())

	return rn
}

func (m *FvAEPgModel) BuildDN(parentDN string) string {
	return parentDN + "/" + m.BuildRN()
}

func (m *FvAEPgModel) ParentDNFromDN(dn string) string {
	rn := m.BuildRN()

	parentDN, _ := strings.CutSuffix(dn, "/"+rn)
	return parentDN
}

func FvAEPgModelFromObject(
	ctx context.Context,
	object *container.Container,
	fallbackModel *FvAEPgModel,
) (FvAEPgModel, diag.Diagnostics) {
	model := NewFvAEPgModelNull()
	var diagnostics diag.Diagnostics

	attributes, ok := modelHelpers.AttributesFromObject(ctx, &diagnostics, object, "fvAEPg")
	if !ok {
		return model, diagnostics
	}
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "annotation", &model.Annotation)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "descr", &model.Descr)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "exceptionTag", &model.ExceptionTag)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "floodOnEncap", &model.FloodOnEncap)
	modelHelpers.DecodeStringAttributeWithEmptyValue(ctx, &diagnostics, attributes, "fwdCtrl", "none", &model.FwdCtrl)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "hasMcastSource", &model.HasMcastSource)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "isAttrBasedEPg", &model.IsAttrBasedEPg)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "matchT", &model.MatchT)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "name", &model.Name)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "nameAlias", &model.NameAlias)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "pcEnfPref", &model.PcEnfPref)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "pcTag", &model.PcTag)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "prefGrMemb", &model.PrefGrMemb)
	modelHelpers.DecodeCustomStringAttribute(ctx, &diagnostics, attributes, "prio", &model.Prio, customTypes.NewFvAEPgPrioStringValue)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "scope", &model.Scope)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "shutdown", &model.Shutdown)
	childObjects := modelHelpers.ChildObjectsByClass(
		ctx,
		&diagnostics,
		object,
		"fvAEPg",
		[]string{
			"fvCrtrn",
			"fvRsAEPgMonPol",
			"fvRsAepAtt",
			"fvRsBd",
			"fvRsCons",
			"fvRsConsIf",
			"fvRsCustQosPol",
			"fvRsDomAtt",
			"fvRsDppPol",
			"fvRsFcPathAtt",
			"fvRsIntraEpg",
			"fvRsNodeAtt",
			"fvRsPathAtt",
			"fvRsProtBy",
			"fvRsProv",
			"fvRsSecInherited",
			"fvRsTrustCtrl",
			"tagAnnotation",
			"tagTag",
		},
	)
	var fallbackFvCrtrn *types.Object
	if fallbackModel != nil {
		fallbackFvCrtrn = &fallbackModel.FvCrtrn
	}
	modelHelpers.DecodeSingletonChild(
		ctx,
		&diagnostics,
		childObjects["fvCrtrn"],
		fallbackFvCrtrn,
		FvCrtrnModelAttributeTypes(),
		"fvAEPg",
		"fvCrtrn",
		NewFvCrtrnModelNull,
		FvCrtrnModelFromObject,
		&model.FvCrtrn,
	)
	var fallbackFvRsAEPgMonPol *types.Object
	if fallbackModel != nil {
		fallbackFvRsAEPgMonPol = &fallbackModel.FvRsAEPgMonPol
	}
	modelHelpers.DecodeSingletonChild(
		ctx,
		&diagnostics,
		childObjects["fvRsAEPgMonPol"],
		fallbackFvRsAEPgMonPol,
		FvRsAEPgMonPolModelAttributeTypes(),
		"fvAEPg",
		"fvRsAEPgMonPol",
		NewFvRsAEPgMonPolModelNull,
		FvRsAEPgMonPolModelFromObject,
		&model.FvRsAEPgMonPol,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsAepAtt"],
		FvRsAepAttModelAttributeTypes(),
		FvRsAepAttModelFromObject,
		&model.FvRsAepAtt,
	)
	var fallbackFvRsBd *types.Object
	if fallbackModel != nil {
		fallbackFvRsBd = &fallbackModel.FvRsBd
	}
	modelHelpers.DecodeSingletonChild(
		ctx,
		&diagnostics,
		childObjects["fvRsBd"],
		fallbackFvRsBd,
		FvRsBdModelAttributeTypes(),
		"fvAEPg",
		"fvRsBd",
		NewFvRsBdModelNull,
		FvRsBdModelFromObject,
		&model.FvRsBd,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsCons"],
		FvRsConsModelAttributeTypes(),
		FvRsConsModelFromObject,
		&model.FvRsCons,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsConsIf"],
		FvRsConsIfModelAttributeTypes(),
		FvRsConsIfModelFromObject,
		&model.FvRsConsIf,
	)
	var fallbackFvRsCustQosPol *types.Object
	if fallbackModel != nil {
		fallbackFvRsCustQosPol = &fallbackModel.FvRsCustQosPol
	}
	modelHelpers.DecodeSingletonChild(
		ctx,
		&diagnostics,
		childObjects["fvRsCustQosPol"],
		fallbackFvRsCustQosPol,
		FvRsCustQosPolModelAttributeTypes(),
		"fvAEPg",
		"fvRsCustQosPol",
		NewFvRsCustQosPolModelNull,
		FvRsCustQosPolModelFromObject,
		&model.FvRsCustQosPol,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsDomAtt"],
		FvRsDomAttModelAttributeTypes(),
		FvRsDomAttModelFromObject,
		&model.FvRsDomAtt,
	)
	var fallbackFvRsDppPol *types.Object
	if fallbackModel != nil {
		fallbackFvRsDppPol = &fallbackModel.FvRsDppPol
	}
	modelHelpers.DecodeSingletonChild(
		ctx,
		&diagnostics,
		childObjects["fvRsDppPol"],
		fallbackFvRsDppPol,
		FvRsDppPolModelAttributeTypes(),
		"fvAEPg",
		"fvRsDppPol",
		NewFvRsDppPolModelNull,
		FvRsDppPolModelFromObject,
		&model.FvRsDppPol,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsFcPathAtt"],
		FvRsFcPathAttModelAttributeTypes(),
		FvRsFcPathAttModelFromObject,
		&model.FvRsFcPathAtt,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsIntraEpg"],
		FvRsIntraEpgModelAttributeTypes(),
		FvRsIntraEpgModelFromObject,
		&model.FvRsIntraEpg,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsNodeAtt"],
		FvRsNodeAttModelAttributeTypes(),
		FvRsNodeAttModelFromObject,
		&model.FvRsNodeAtt,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsPathAtt"],
		FvRsPathAttModelAttributeTypes(),
		FvRsPathAttModelFromObject,
		&model.FvRsPathAtt,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsProtBy"],
		FvRsProtByModelAttributeTypes(),
		FvRsProtByModelFromObject,
		&model.FvRsProtBy,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsProv"],
		FvRsProvModelAttributeTypes(),
		FvRsProvModelFromObject,
		&model.FvRsProv,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["fvRsSecInherited"],
		FvRsSecInheritedModelAttributeTypes(),
		FvRsSecInheritedModelFromObject,
		&model.FvRsSecInherited,
	)
	var fallbackFvRsTrustCtrl *types.Object
	if fallbackModel != nil {
		fallbackFvRsTrustCtrl = &fallbackModel.FvRsTrustCtrl
	}
	modelHelpers.DecodeSingletonChild(
		ctx,
		&diagnostics,
		childObjects["fvRsTrustCtrl"],
		fallbackFvRsTrustCtrl,
		FvRsTrustCtrlModelAttributeTypes(),
		"fvAEPg",
		"fvRsTrustCtrl",
		NewFvRsTrustCtrlModelNull,
		FvRsTrustCtrlModelFromObject,
		&model.FvRsTrustCtrl,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["tagAnnotation"],
		TagAnnotationModelAttributeTypes(),
		TagAnnotationModelFromObject,
		&model.TagAnnotation,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["tagTag"],
		TagTagModelAttributeTypes(),
		TagTagModelFromObject,
		&model.TagTag,
	)

	return model, diagnostics
}

func FvAEPgModelFromResponse(
	ctx context.Context,
	response *container.Container,
	fallbackModel *FvAEPgModel,
) (*FvAEPgModel, string, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	model, dn := modelHelpers.ModelFromResponse(ctx, &diagnostics, response, "fvAEPg", fallbackModel, FvAEPgModelFromObject)
	return model, dn, diagnostics
}

func (m *FvAEPgModel) BuildPayloadObject(
	ctx context.Context,
	priorState *FvAEPgModel,
	nested bool,
	defaultAnnotation string,
) (map[string]any, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	attributes := map[string]any{}
	children := make([]map[string]any, 0)
	if !modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "annotation", m.Annotation) && nested {
		attributes["annotation"] = defaultAnnotation
	}
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "descr", m.Descr)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "exceptionTag", m.ExceptionTag)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "floodOnEncap", m.FloodOnEncap)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "fwdCtrl", m.FwdCtrl)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "hasMcastSource", m.HasMcastSource)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "isAttrBasedEPg", m.IsAttrBasedEPg)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "matchT", m.MatchT)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "name", m.Name)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "nameAlias", m.NameAlias)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "pcEnfPref", m.PcEnfPref)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "prefGrMemb", m.PrefGrMemb)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "prio", m.Prio)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "shutdown", m.Shutdown)
	var priorFvCrtrn *types.Object
	if priorState != nil {
		priorFvCrtrn = &priorState.FvCrtrn
	}
	fvCrtrnPayloads, ok := modelHelpers.BuildSingletonChildPayload(
		ctx,
		&diagnostics,
		m.FvCrtrn,
		priorFvCrtrn,
		"fvCrtrn",
		"FvCrtrn object defined by epg_useg_block_statement cannot be deleted",
		defaultAnnotation,
		(*FvCrtrnModel).BuildPayloadObject,
		(*FvCrtrnModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvCrtrnPayloads...)
	var priorFvRsAEPgMonPol *types.Object
	if priorState != nil {
		priorFvRsAEPgMonPol = &priorState.FvRsAEPgMonPol
	}
	fvRsAEPgMonPolPayloads, ok := modelHelpers.BuildSingletonChildPayload(
		ctx,
		&diagnostics,
		m.FvRsAEPgMonPol,
		priorFvRsAEPgMonPol,
		"fvRsAEPgMonPol",
		"FvRsAEPgMonPol object defined by relation_to_monitoring_policy cannot be deleted",
		defaultAnnotation,
		(*FvRsAEPgMonPolModel).BuildPayloadObject,
		(*FvRsAEPgMonPolModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsAEPgMonPolPayloads...)
	var priorFvRsAepAtt *types.Set
	if priorState != nil {
		priorFvRsAepAtt = &priorState.FvRsAepAtt
	}
	fvRsAepAttPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsAepAtt,
		priorFvRsAepAtt,
		"fvRsAepAtt",
		"FvRsAepAtt object defined by relation_to_attachable_access_entity_profiles cannot be deleted",
		defaultAnnotation,
		(*FvRsAepAttModel).BuildRN,
		(*FvRsAepAttModel).BuildPayloadObject,
		(*FvRsAepAttModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsAepAttPayloads...)
	var priorFvRsBd *types.Object
	if priorState != nil {
		priorFvRsBd = &priorState.FvRsBd
	}
	fvRsBdPayloads, ok := modelHelpers.BuildSingletonChildPayload(
		ctx,
		&diagnostics,
		m.FvRsBd,
		priorFvRsBd,
		"fvRsBd",
		"FvRsBd object defined by relation_to_bridge_domain cannot be deleted",
		defaultAnnotation,
		(*FvRsBdModel).BuildPayloadObject,
		nil,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsBdPayloads...)
	var priorFvRsCons *types.Set
	if priorState != nil {
		priorFvRsCons = &priorState.FvRsCons
	}
	fvRsConsPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsCons,
		priorFvRsCons,
		"fvRsCons",
		"FvRsCons object defined by relation_to_consumed_contracts cannot be deleted",
		defaultAnnotation,
		(*FvRsConsModel).BuildRN,
		(*FvRsConsModel).BuildPayloadObject,
		(*FvRsConsModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsConsPayloads...)
	var priorFvRsConsIf *types.Set
	if priorState != nil {
		priorFvRsConsIf = &priorState.FvRsConsIf
	}
	fvRsConsIfPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsConsIf,
		priorFvRsConsIf,
		"fvRsConsIf",
		"FvRsConsIf object defined by relation_to_imported_contracts cannot be deleted",
		defaultAnnotation,
		(*FvRsConsIfModel).BuildRN,
		(*FvRsConsIfModel).BuildPayloadObject,
		(*FvRsConsIfModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsConsIfPayloads...)
	var priorFvRsCustQosPol *types.Object
	if priorState != nil {
		priorFvRsCustQosPol = &priorState.FvRsCustQosPol
	}
	fvRsCustQosPolPayloads, ok := modelHelpers.BuildSingletonChildPayload(
		ctx,
		&diagnostics,
		m.FvRsCustQosPol,
		priorFvRsCustQosPol,
		"fvRsCustQosPol",
		"FvRsCustQosPol object defined by relation_to_custom_qos_policy cannot be deleted",
		defaultAnnotation,
		(*FvRsCustQosPolModel).BuildPayloadObject,
		nil,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsCustQosPolPayloads...)
	var priorFvRsDomAtt *types.Set
	if priorState != nil {
		priorFvRsDomAtt = &priorState.FvRsDomAtt
	}
	fvRsDomAttPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsDomAtt,
		priorFvRsDomAtt,
		"fvRsDomAtt",
		"FvRsDomAtt object defined by relation_to_domains cannot be deleted",
		defaultAnnotation,
		(*FvRsDomAttModel).BuildRN,
		(*FvRsDomAttModel).BuildPayloadObject,
		(*FvRsDomAttModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsDomAttPayloads...)
	var priorFvRsDppPol *types.Object
	if priorState != nil {
		priorFvRsDppPol = &priorState.FvRsDppPol
	}
	fvRsDppPolPayloads, ok := modelHelpers.BuildSingletonChildPayload(
		ctx,
		&diagnostics,
		m.FvRsDppPol,
		priorFvRsDppPol,
		"fvRsDppPol",
		"FvRsDppPol object defined by relation_to_data_plane_policing_policy cannot be deleted",
		defaultAnnotation,
		(*FvRsDppPolModel).BuildPayloadObject,
		(*FvRsDppPolModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsDppPolPayloads...)
	var priorFvRsFcPathAtt *types.Set
	if priorState != nil {
		priorFvRsFcPathAtt = &priorState.FvRsFcPathAtt
	}
	fvRsFcPathAttPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsFcPathAtt,
		priorFvRsFcPathAtt,
		"fvRsFcPathAtt",
		"FvRsFcPathAtt object defined by relation_to_fibre_channel_paths cannot be deleted",
		defaultAnnotation,
		(*FvRsFcPathAttModel).BuildRN,
		(*FvRsFcPathAttModel).BuildPayloadObject,
		(*FvRsFcPathAttModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsFcPathAttPayloads...)
	var priorFvRsIntraEpg *types.Set
	if priorState != nil {
		priorFvRsIntraEpg = &priorState.FvRsIntraEpg
	}
	fvRsIntraEpgPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsIntraEpg,
		priorFvRsIntraEpg,
		"fvRsIntraEpg",
		"FvRsIntraEpg object defined by relation_to_intra_epg_contracts cannot be deleted",
		defaultAnnotation,
		(*FvRsIntraEpgModel).BuildRN,
		(*FvRsIntraEpgModel).BuildPayloadObject,
		(*FvRsIntraEpgModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsIntraEpgPayloads...)
	var priorFvRsNodeAtt *types.Set
	if priorState != nil {
		priorFvRsNodeAtt = &priorState.FvRsNodeAtt
	}
	fvRsNodeAttPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsNodeAtt,
		priorFvRsNodeAtt,
		"fvRsNodeAtt",
		"FvRsNodeAtt object defined by relation_to_static_leafs cannot be deleted",
		defaultAnnotation,
		(*FvRsNodeAttModel).BuildRN,
		(*FvRsNodeAttModel).BuildPayloadObject,
		(*FvRsNodeAttModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsNodeAttPayloads...)
	var priorFvRsPathAtt *types.Set
	if priorState != nil {
		priorFvRsPathAtt = &priorState.FvRsPathAtt
	}
	fvRsPathAttPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsPathAtt,
		priorFvRsPathAtt,
		"fvRsPathAtt",
		"FvRsPathAtt object defined by relation_to_static_paths cannot be deleted",
		defaultAnnotation,
		(*FvRsPathAttModel).BuildRN,
		(*FvRsPathAttModel).BuildPayloadObject,
		(*FvRsPathAttModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsPathAttPayloads...)
	var priorFvRsProtBy *types.Set
	if priorState != nil {
		priorFvRsProtBy = &priorState.FvRsProtBy
	}
	fvRsProtByPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsProtBy,
		priorFvRsProtBy,
		"fvRsProtBy",
		"FvRsProtBy object defined by relation_to_taboo_contracts cannot be deleted",
		defaultAnnotation,
		(*FvRsProtByModel).BuildRN,
		(*FvRsProtByModel).BuildPayloadObject,
		(*FvRsProtByModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsProtByPayloads...)
	var priorFvRsProv *types.Set
	if priorState != nil {
		priorFvRsProv = &priorState.FvRsProv
	}
	fvRsProvPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsProv,
		priorFvRsProv,
		"fvRsProv",
		"FvRsProv object defined by relation_to_provided_contracts cannot be deleted",
		defaultAnnotation,
		(*FvRsProvModel).BuildRN,
		(*FvRsProvModel).BuildPayloadObject,
		(*FvRsProvModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsProvPayloads...)
	var priorFvRsSecInherited *types.Set
	if priorState != nil {
		priorFvRsSecInherited = &priorState.FvRsSecInherited
	}
	fvRsSecInheritedPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.FvRsSecInherited,
		priorFvRsSecInherited,
		"fvRsSecInherited",
		"FvRsSecInherited object defined by relation_to_contract_masters cannot be deleted",
		defaultAnnotation,
		(*FvRsSecInheritedModel).BuildRN,
		(*FvRsSecInheritedModel).BuildPayloadObject,
		(*FvRsSecInheritedModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsSecInheritedPayloads...)
	var priorFvRsTrustCtrl *types.Object
	if priorState != nil {
		priorFvRsTrustCtrl = &priorState.FvRsTrustCtrl
	}
	fvRsTrustCtrlPayloads, ok := modelHelpers.BuildSingletonChildPayload(
		ctx,
		&diagnostics,
		m.FvRsTrustCtrl,
		priorFvRsTrustCtrl,
		"fvRsTrustCtrl",
		"FvRsTrustCtrl object defined by relation_to_trust_control_policy cannot be deleted",
		defaultAnnotation,
		(*FvRsTrustCtrlModel).BuildPayloadObject,
		(*FvRsTrustCtrlModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, fvRsTrustCtrlPayloads...)
	var priorTagAnnotation *types.Set
	if priorState != nil {
		priorTagAnnotation = &priorState.TagAnnotation
	}
	tagAnnotationPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.TagAnnotation,
		priorTagAnnotation,
		"tagAnnotation",
		"TagAnnotation object defined by annotations cannot be deleted",
		defaultAnnotation,
		(*TagAnnotationModel).BuildRN,
		(*TagAnnotationModel).BuildPayloadObject,
		(*TagAnnotationModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, tagAnnotationPayloads...)
	var priorTagTag *types.Set
	if priorState != nil {
		priorTagTag = &priorState.TagTag
	}
	tagTagPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.TagTag,
		priorTagTag,
		"tagTag",
		"TagTag object defined by tags cannot be deleted",
		defaultAnnotation,
		(*TagTagModel).BuildRN,
		(*TagTagModel).BuildPayloadObject,
		(*TagTagModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, tagTagPayloads...)

	return modelHelpers.NewPayloadObject(
		ctx,
		&diagnostics,
		attributes,
		children,
		true,
	), diagnostics
}

func (m *FvAEPgModel) BuildNestedDeletePayloadObject(
	ctx context.Context,
	diagnostics *diag.Diagnostics,
) map[string]any {
	attributes := map[string]any{}
	attributes["name"] = m.Name.ValueString()
	return modelHelpers.NewNestedDeletePayloadObject(ctx, diagnostics, attributes)
}

type FvAEPgResourceModel struct {
	FvAEPgModel

	ID       types.String `tfsdk:"id"`
	ParentDn types.String `tfsdk:"parent_dn"`
}

func NewFvAEPgResourceModelNull() FvAEPgResourceModel {
	return FvAEPgResourceModel{
		FvAEPgModel: NewFvAEPgModelNull(),
		ID:          types.StringNull(),
		ParentDn:    types.StringNull(),
	}
}

func (m *FvAEPgResourceModel) SetIDFromDN(dn string) {
	m.ID = types.StringValue(dn)
}

func (m *FvAEPgResourceModel) SetFromResponse(
	ctx context.Context,
	response *container.Container,
) (bool, diag.Diagnostics) {
	fallbackModel := m.FvAEPgModel
	model, dn, diagnostics := FvAEPgModelFromResponse(ctx, response, &fallbackModel)
	found := model != nil
	if diagnostics.HasError() || !found {
		return found, diagnostics
	}

	m.FvAEPgModel = *model
	m.ID = types.StringValue(dn)
	m.ParentDn = types.StringValue(model.ParentDNFromDN(dn))
	return true, diagnostics
}

func (m *FvAEPgResourceModel) BuildPayload(
	ctx context.Context,
	priorState *FvAEPgModel,
	create bool,
	markCreated bool,
	defaultAnnotation string,
) (*container.Container, diag.Diagnostics) {
	payloadObject, diagnostics := m.BuildPayloadObject(ctx, priorState, false, defaultAnnotation)
	if diagnostics.HasError() {
		return nil, diagnostics
	}
	if markCreated {
		payloadObject["attributes"].(map[string]any)["status"] = "created"
	}
	payloadEnvelope := map[string]any{"fvAEPg": payloadObject}
	jsonPayload := modelHelpers.NewPayloadContainer(ctx, &diagnostics, payloadEnvelope, "JSON payload")
	return jsonPayload, diagnostics
}

func (m *FvAEPgResourceModel) BuildDeletePayload(ctx context.Context) (*container.Container, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	payload := modelHelpers.NewDeletePayload(ctx, &diagnostics, "fvAEPg", m.ID.ValueString())
	return payload, diagnostics
}

type FvAEPgDataSourceModel struct {
	FvAEPgModel

	ID       types.String `tfsdk:"id"`
	ParentDn types.String `tfsdk:"parent_dn"`
}

func NewFvAEPgDataSourceModelNull() FvAEPgDataSourceModel {
	return FvAEPgDataSourceModel{
		FvAEPgModel: NewFvAEPgModelNull(),
		ID:          types.StringNull(),
		ParentDn:    types.StringNull(),
	}
}

func (m *FvAEPgDataSourceModel) SetIDFromDN(dn string) {
	m.ID = types.StringValue(dn)
}

func (m *FvAEPgDataSourceModel) SetFromResponse(
	ctx context.Context,
	response *container.Container,
) (bool, diag.Diagnostics) {
	fallbackModel := m.FvAEPgModel
	model, dn, diagnostics := FvAEPgModelFromResponse(ctx, response, &fallbackModel)
	found := model != nil
	if diagnostics.HasError() || !found {
		return found, diagnostics
	}

	m.FvAEPgModel = *model
	m.ID = types.StringValue(dn)
	m.ParentDn = types.StringValue(model.ParentDNFromDN(dn))
	return true, diagnostics
}
