// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type FvIpAttrModel struct{}

type FvIpAttrResourceModel struct {
	FvIpAttrModel

	ID types.String `tfsdk:"id"`
}

type FvIpAttrDataSourceModel struct {
	FvIpAttrModel

	ID types.String `tfsdk:"id"`
}
