// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type FvRsConsModel struct{}

type FvRsConsResourceModel struct {
	FvRsConsModel

	ID types.String `tfsdk:"id"`
}

type FvRsConsDataSourceModel struct {
	FvRsConsModel

	ID types.String `tfsdk:"id"`
}
