// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type FvRsCtxToEigrpCtxAfPolModel struct{}

type FvRsCtxToEigrpCtxAfPolResourceModel struct {
	FvRsCtxToEigrpCtxAfPolModel

	ID types.String `tfsdk:"id"`
}

type FvRsCtxToEigrpCtxAfPolDataSourceModel struct {
	FvRsCtxToEigrpCtxAfPolModel

	ID types.String `tfsdk:"id"`
}
