// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type FvRsBDToNetflowMonitorPolModel struct{}

type FvRsBDToNetflowMonitorPolResourceModel struct {
	FvRsBDToNetflowMonitorPolModel

	ID types.String `tfsdk:"id"`
}

type FvRsBDToNetflowMonitorPolDataSourceModel struct {
	FvRsBDToNetflowMonitorPolModel

	ID types.String `tfsdk:"id"`
}
