// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type L2PortAuthPolModel struct{}

type L2PortAuthPolResourceModel struct {
	L2PortAuthPolModel

	ID types.String `tfsdk:"id"`
}

type L2PortAuthPolDataSourceModel struct {
	L2PortAuthPolModel

	ID types.String `tfsdk:"id"`
}
