// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/main/README.md).

package models

import (
	"context"
	"strings"

	"github.com/ciscoecosystem/aci-go-client/v2/container"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	modelHelpers "github.com/CiscoDevNet/terraform-provider-aci/v2/internal/provider/models/helpers"
)

type L3extRsRedistributePolModel struct {
	Annotation          types.String `tfsdk:"annotation"`
	Src                 types.String `tfsdk:"source"`
	TnRtctrlProfileName types.String `tfsdk:"route_control_profile_name"`
	TagAnnotation       types.Set    `tfsdk:"annotations"`
	TagTag              types.Set    `tfsdk:"tags"`
}

func L3extRsRedistributePolModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"annotation":                 types.StringType,
		"source":                     types.StringType,
		"route_control_profile_name": types.StringType,
		"annotations": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: TagAnnotationModelAttributeTypes(),
			},
		},
		"tags": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: TagTagModelAttributeTypes(),
			},
		},
	}
}

func NewL3extRsRedistributePolModelNull() L3extRsRedistributePolModel {
	return L3extRsRedistributePolModel{
		Annotation:          types.StringNull(),
		Src:                 types.StringNull(),
		TnRtctrlProfileName: types.StringNull(),
		TagAnnotation: types.SetNull(
			types.ObjectType{
				AttrTypes: TagAnnotationModelAttributeTypes(),
			},
		),
		TagTag: types.SetNull(
			types.ObjectType{
				AttrTypes: TagTagModelAttributeTypes(),
			},
		),
	}
}

func (m *L3extRsRedistributePolModel) BuildRN() string {
	rn := "rsredistributePol-[{tnRtctrlProfileName}]-{src}"
	rn = strings.ReplaceAll(rn, "{src}", m.Src.ValueString())
	rn = strings.ReplaceAll(rn, "{tnRtctrlProfileName}", m.TnRtctrlProfileName.ValueString())

	return rn
}

func (m *L3extRsRedistributePolModel) BuildDN(parentDN string) string {
	return parentDN + "/" + m.BuildRN()
}

func (m *L3extRsRedistributePolModel) ParentDNFromDN(dn string) string {
	rn := m.BuildRN()

	parentDN, _ := strings.CutSuffix(dn, "/"+rn)
	return parentDN
}

func L3extRsRedistributePolModelFromObject(
	ctx context.Context,
	object *container.Container,
	fallbackModel *L3extRsRedistributePolModel,
) (L3extRsRedistributePolModel, diag.Diagnostics) {
	model := NewL3extRsRedistributePolModelNull()
	var diagnostics diag.Diagnostics

	attributes, ok := modelHelpers.AttributesFromObject(ctx, &diagnostics, object, "l3extRsRedistributePol")
	if !ok {
		return model, diagnostics
	}
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "annotation", &model.Annotation)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "src", &model.Src)
	modelHelpers.DecodeStringAttribute(ctx, &diagnostics, attributes, "tnRtctrlProfileName", &model.TnRtctrlProfileName)
	childObjects := modelHelpers.ChildObjectsByClass(
		ctx,
		&diagnostics,
		object,
		"l3extRsRedistributePol",
		[]string{
			"tagAnnotation",
			"tagTag",
		},
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["tagAnnotation"],
		TagAnnotationModelAttributeTypes(),
		TagAnnotationModelFromObject,
		&model.TagAnnotation,
	)
	modelHelpers.DecodeRepeatedChildren(
		ctx,
		&diagnostics,
		childObjects["tagTag"],
		TagTagModelAttributeTypes(),
		TagTagModelFromObject,
		&model.TagTag,
	)

	return model, diagnostics
}

func L3extRsRedistributePolModelFromResponse(
	ctx context.Context,
	response *container.Container,
	fallbackModel *L3extRsRedistributePolModel,
) (*L3extRsRedistributePolModel, string, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	model, dn := modelHelpers.ModelFromResponse(ctx, &diagnostics, response, "l3extRsRedistributePol", fallbackModel, L3extRsRedistributePolModelFromObject)
	return model, dn, diagnostics
}

func (m *L3extRsRedistributePolModel) BuildPayloadObject(
	ctx context.Context,
	priorState *L3extRsRedistributePolModel,
	nested bool,
	defaultAnnotation string,
) (map[string]any, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	attributes := map[string]any{}
	children := make([]map[string]any, 0)
	if !modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "annotation", m.Annotation) && nested {
		attributes["annotation"] = defaultAnnotation
	}
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "src", m.Src)
	modelHelpers.AddPayloadStringAttribute(ctx, &diagnostics, attributes, "tnRtctrlProfileName", m.TnRtctrlProfileName)
	var priorTagAnnotation *types.Set
	if priorState != nil {
		priorTagAnnotation = &priorState.TagAnnotation
	}
	tagAnnotationPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.TagAnnotation,
		priorTagAnnotation,
		"tagAnnotation",
		"TagAnnotation object defined by annotations cannot be deleted",
		defaultAnnotation,
		(*TagAnnotationModel).BuildRN,
		(*TagAnnotationModel).BuildPayloadObject,
		(*TagAnnotationModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, tagAnnotationPayloads...)
	var priorTagTag *types.Set
	if priorState != nil {
		priorTagTag = &priorState.TagTag
	}
	tagTagPayloads, ok := modelHelpers.BuildRepeatedChildPayloads(
		ctx,
		&diagnostics,
		m.TagTag,
		priorTagTag,
		"tagTag",
		"TagTag object defined by tags cannot be deleted",
		defaultAnnotation,
		(*TagTagModel).BuildRN,
		(*TagTagModel).BuildPayloadObject,
		(*TagTagModel).BuildNestedDeletePayloadObject,
	)
	if !ok {
		return nil, diagnostics
	}
	children = append(children, tagTagPayloads...)

	return modelHelpers.NewPayloadObject(
		ctx,
		&diagnostics,
		attributes,
		children,
		true,
	), diagnostics
}

func (m *L3extRsRedistributePolModel) BuildNestedDeletePayloadObject(
	ctx context.Context,
	diagnostics *diag.Diagnostics,
) map[string]any {
	attributes := map[string]any{}
	attributes["src"] = m.Src.ValueString()
	attributes["tnRtctrlProfileName"] = m.TnRtctrlProfileName.ValueString()
	return modelHelpers.NewNestedDeletePayloadObject(ctx, diagnostics, attributes)
}

type L3extRsRedistributePolResourceModel struct {
	L3extRsRedistributePolModel

	ID       types.String `tfsdk:"id"`
	ParentDn types.String `tfsdk:"parent_dn"`
}

func NewL3extRsRedistributePolResourceModelNull() L3extRsRedistributePolResourceModel {
	return L3extRsRedistributePolResourceModel{
		L3extRsRedistributePolModel: NewL3extRsRedistributePolModelNull(),
		ID:                          types.StringNull(),
		ParentDn:                    types.StringNull(),
	}
}

func (m *L3extRsRedistributePolResourceModel) SetIDFromDN(dn string) {
	m.ID = types.StringValue(dn)
}

func (m *L3extRsRedistributePolResourceModel) SetFromResponse(
	ctx context.Context,
	response *container.Container,
) (bool, diag.Diagnostics) {
	fallbackModel := m.L3extRsRedistributePolModel
	model, dn, diagnostics := L3extRsRedistributePolModelFromResponse(ctx, response, &fallbackModel)
	found := model != nil
	if diagnostics.HasError() || !found {
		return found, diagnostics
	}

	m.L3extRsRedistributePolModel = *model
	m.ID = types.StringValue(dn)
	m.ParentDn = types.StringValue(model.ParentDNFromDN(dn))
	return true, diagnostics
}

func (m *L3extRsRedistributePolResourceModel) BuildPayload(
	ctx context.Context,
	priorState *L3extRsRedistributePolModel,
	create bool,
	markCreated bool,
	defaultAnnotation string,
) (*container.Container, diag.Diagnostics) {
	payloadObject, diagnostics := m.BuildPayloadObject(ctx, priorState, false, defaultAnnotation)
	if diagnostics.HasError() {
		return nil, diagnostics
	}
	if markCreated {
		payloadObject["attributes"].(map[string]any)["status"] = "created"
	}
	payloadEnvelope := map[string]any{"l3extRsRedistributePol": payloadObject}
	jsonPayload := modelHelpers.NewPayloadContainer(ctx, &diagnostics, payloadEnvelope, "JSON payload")
	return jsonPayload, diagnostics
}

func (m *L3extRsRedistributePolResourceModel) BuildDeletePayload(ctx context.Context) (*container.Container, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	payload := modelHelpers.NewDeletePayload(ctx, &diagnostics, "l3extRsRedistributePol", m.ID.ValueString())
	return payload, diagnostics
}

type L3extRsRedistributePolDataSourceModel struct {
	L3extRsRedistributePolModel

	ID       types.String `tfsdk:"id"`
	ParentDn types.String `tfsdk:"parent_dn"`
}

func NewL3extRsRedistributePolDataSourceModelNull() L3extRsRedistributePolDataSourceModel {
	return L3extRsRedistributePolDataSourceModel{
		L3extRsRedistributePolModel: NewL3extRsRedistributePolModelNull(),
		ID:                          types.StringNull(),
		ParentDn:                    types.StringNull(),
	}
}

func (m *L3extRsRedistributePolDataSourceModel) SetIDFromDN(dn string) {
	m.ID = types.StringValue(dn)
}

func (m *L3extRsRedistributePolDataSourceModel) SetFromResponse(
	ctx context.Context,
	response *container.Container,
) (bool, diag.Diagnostics) {
	fallbackModel := m.L3extRsRedistributePolModel
	model, dn, diagnostics := L3extRsRedistributePolModelFromResponse(ctx, response, &fallbackModel)
	found := model != nil
	if diagnostics.HasError() || !found {
		return found, diagnostics
	}

	m.L3extRsRedistributePolModel = *model
	m.ID = types.StringValue(dn)
	m.ParentDn = types.StringValue(model.ParentDNFromDN(dn))
	return true, diagnostics
}
