// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type L3extInstPModel struct{}

type L3extInstPResourceModel struct {
	L3extInstPModel

	ID types.String `tfsdk:"id"`
}

type L3extInstPDataSourceModel struct {
	L3extInstPModel

	ID types.String `tfsdk:"id"`
}
