// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type NetflowRecordPolModel struct{}

type NetflowRecordPolResourceModel struct {
	NetflowRecordPolModel

	ID types.String `tfsdk:"id"`
}

type NetflowRecordPolDataSourceModel struct {
	NetflowRecordPolModel

	ID types.String `tfsdk:"id"`
}
