// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type QosNodropDscpMatchIfPolModel struct{}

type QosNodropDscpMatchIfPolResourceModel struct {
	QosNodropDscpMatchIfPolModel

	ID types.String `tfsdk:"id"`
}

type QosNodropDscpMatchIfPolDataSourceModel struct {
	QosNodropDscpMatchIfPolModel

	ID types.String `tfsdk:"id"`
}
