// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type VmmUplinkPContModel struct{}

type VmmUplinkPContResourceModel struct {
	VmmUplinkPContModel

	ID types.String `tfsdk:"id"`
}

type VmmUplinkPContDataSourceModel struct {
	VmmUplinkPContModel

	ID types.String `tfsdk:"id"`
}
