// Code generated by "gen/generator.go"; DO NOT EDIT.

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type VzOOBBrCPModel struct{}

type VzOOBBrCPResourceModel struct {
	VzOOBBrCPModel

	ID types.String `tfsdk:"id"`
}

type VzOOBBrCPDataSourceModel struct {
	VzOOBBrCPModel

	ID types.String `tfsdk:"id"`
}
