// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceInfraSHPortSWithInfraSpAccPortP(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "2.0(1m)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:             testConfigInfraSHPortSDataSourceDependencyWithInfraSpAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.aci_spine_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("data.aci_spine_access_port_selector.test", "port_selector_type", "ALL"),
					resource.TestCheckResourceAttr("data.aci_spine_access_port_selector.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("data.aci_spine_access_port_selector.test", "description", ""),
					resource.TestCheckResourceAttr("data.aci_spine_access_port_selector.test", "name_alias", ""),
					resource.TestCheckResourceAttr("data.aci_spine_access_port_selector.test", "owner_key", ""),
					resource.TestCheckResourceAttr("data.aci_spine_access_port_selector.test", "owner_tag", ""),
				),
			},
			{
				Config:      testConfigInfraSHPortSNotExistingInfraSpAccPortP,
				ExpectError: regexp.MustCompile("Failed to read aci_spine_access_port_selector data source"),
			},
		},
	})
}

const testConfigInfraSHPortSDataSourceDependencyWithInfraSpAccPortP = testConfigInfraSHPortSMinDependencyWithInfraSpAccPortP + `
data "aci_spine_access_port_selector" "test" {
  parent_dn = aci_spine_interface_profile.test.id
  name = "test_name"
  port_selector_type = "ALL"
  depends_on = [aci_spine_access_port_selector.test]
}
`

const testConfigInfraSHPortSNotExistingInfraSpAccPortP = testConfigInfraSpAccPortPMin + `
data "aci_spine_access_port_selector" "test_non_existing" {
  parent_dn = aci_spine_interface_profile.test.id
  name = "non_existing_name"
  port_selector_type = "ALL"
}
`
