// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceL3extConsLblWithL3extOut(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:             testConfigL3extConsLblDataSourceDependencyWithL3extOut,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "name", "test_name"),
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "description", ""),
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "name_alias", ""),
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "owner", "infra"),
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "owner_key", ""),
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "owner_tag", ""),
					resource.TestCheckResourceAttr("data.aci_l3out_consumer_label.test", "tag", "yellow-green"),
				),
			},
		},
	})
}

const testConfigL3extConsLblDataSourceDependencyWithL3extOut = testConfigL3extConsLblMinDependencyWithL3extOut + `
data "aci_l3out_consumer_label" "test" {
  parent_dn = aci_l3_outside.test.id
  name = "test_name"
  depends_on = [aci_l3out_consumer_label.test]
}
`
