// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceFvRsSecInheritedWithFvAEPg(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:             testConfigFvRsSecInheritedDataSourceDependencyWithFvAEPg,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.aci_relation_to_contract_master.test", "target_dn", "uni/tn-test_tenant/ap-test_ap/epg-epg_2"),
					resource.TestCheckResourceAttr("data.aci_relation_to_contract_master.test", "annotation", "orchestrator:terraform"),
				),
			},
			{
				Config:      testConfigFvRsSecInheritedNotExistingFvAEPg,
				ExpectError: regexp.MustCompile("Failed to read aci_relation_to_contract_master data source"),
			},
		},
	})
}
func TestAccDataSourceFvRsSecInheritedWithFvESg(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:             testConfigFvRsSecInheritedDataSourceDependencyWithFvESg,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.aci_relation_to_contract_master.test", "target_dn", "uni/tn-test_tenant/ap-test_ap/esg-esg_0"),
					resource.TestCheckResourceAttr("data.aci_relation_to_contract_master.test", "annotation", "orchestrator:terraform"),
				),
			},
			{
				Config:      testConfigFvRsSecInheritedNotExistingFvESg,
				ExpectError: regexp.MustCompile("Failed to read aci_relation_to_contract_master data source"),
			},
		},
	})
}

const testConfigFvRsSecInheritedDataSourceDependencyWithFvAEPg = testConfigFvRsSecInheritedMinDependencyWithFvAEPg + `
data "aci_relation_to_contract_master" "test" {
  parent_dn = aci_application_epg.test.id
  target_dn = aci_application_epg.test_2.id
  depends_on = [aci_relation_to_contract_master.test]
}
`

const testConfigFvRsSecInheritedNotExistingFvAEPg = testConfigFvAEPgMinDependencyWithFvAp + `
data "aci_relation_to_contract_master" "test_non_existing" {
  parent_dn = aci_application_epg.test.id
  target_dn = "uni/tn-test_tenant/ap-test_ap/epg-epg_2_not_existing"
}
`
const testConfigFvRsSecInheritedDataSourceDependencyWithFvESg = testConfigFvRsSecInheritedMinDependencyWithFvESg + `
data "aci_relation_to_contract_master" "test" {
  parent_dn = aci_endpoint_security_group.test.id
  target_dn = aci_endpoint_security_group.test_0.id
  depends_on = [aci_relation_to_contract_master.test]
}
`

const testConfigFvRsSecInheritedNotExistingFvESg = testConfigFvESgMinDependencyWithFvAp + `
data "aci_relation_to_contract_master" "test_non_existing" {
  parent_dn = aci_endpoint_security_group.test.id
  target_dn = "uni/tn-test_tenant/ap-test_ap/esg-esg_0_not_existing"
}
`
