// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccResourceInfraHPortSWithInfraAccPortP(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraAccPortPAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_tag", ""),
				),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "false")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:      testConfigInfraHPortSMinDependencyWithInfraAccPortPAllowExisting,
				ExpectError: regexp.MustCompile("Object Already Exists"),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "true")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraAccPortPAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_tag", ""),
				),
			},
		},
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", ""),
				),
			},
			// Update with all config and verify default APIC values
			{
				Config:             testConfigInfraHPortSAllDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "annotation"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", "description_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", "name_alias_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", "owner_key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", "owner_tag_1"),
				),
			},
			// Update with minimum config and verify config is unchanged
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
				),
			},
			// Update with empty strings config or default value
			{
				Config:             testConfigInfraHPortSResetDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", ""),
				),
			},
			// Import testing
			{
				ResourceName:      "aci_access_port_selector.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children
			{
				Config:             testConfigInfraHPortSChildrenDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotation", "annotation_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.fex_id", "102"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.target_dn", "uni/infra/funcprof/accportgrp-leaf_access_port_policy_group_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.value", "test_value"),
				),
			},
			// Refresh State before import testing to ensure that the state is up to date
			{
				RefreshState:       true,
				ExpectNonEmptyPlan: false,
			},
			// Import testing with children
			{
				ResourceName:      "aci_access_port_selector.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children removed from config
			{
				Config:             testConfigInfraHPortSChildrenRemoveFromConfigDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.#", "2"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotation", "annotation_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.#", "2"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.#", "2"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.fex_id", "102"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.target_dn", "uni/infra/funcprof/accportgrp-leaf_access_port_policy_group_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.#", "2"),
				),
			},
			// Update with children first child removed
			{
				Config:             testConfigInfraHPortSChildrenRemoveOneDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.#", "1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.#", "1"),
				),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue("aci_access_port_selector.test",
						tfjsonpath.New("relation_to_leaf_access_port_policy_group"),
						knownvalue.MapExact(
							map[string]knownvalue.Check{
								"annotation":  knownvalue.Null(),
								"annotations": knownvalue.Null(),
								"tags":        knownvalue.Null(),
								"fex_id":      knownvalue.Null(),
								"target_dn":   knownvalue.Null(),
							},
						),
					),
				},
			},
			// Update with all children removed
			{
				Config:             testConfigInfraHPortSChildrenRemoveAllDependencyWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.#", "0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.#", "0"),
				),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue("aci_access_port_selector.test",
						tfjsonpath.New("relation_to_leaf_access_port_policy_group"),
						knownvalue.MapExact(
							map[string]knownvalue.Check{
								"annotation":  knownvalue.Null(),
								"annotations": knownvalue.Null(),
								"tags":        knownvalue.Null(),
								"fex_id":      knownvalue.Null(),
								"target_dn":   knownvalue.Null(),
							},
						),
					),
				},
			},
			// Update with legacy attribute config
			{
				Config:             testConfigInfraHPortSLegacyAttributesWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
			},
		},
		CheckDestroy: testCheckResourceDestroy,
	})
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with legacy attribute config
			{
				Config:             testConfigInfraHPortSLegacyAttributesWithInfraAccPortP,
				ExpectNonEmptyPlan: false,
			},
		},
		CheckDestroy: testCheckResourceDestroy,
	})
}
func TestAccResourceInfraHPortSWithInfraFexP(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraFexPAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_tag", ""),
				),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "false")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:      testConfigInfraHPortSMinDependencyWithInfraFexPAllowExisting,
				ExpectError: regexp.MustCompile("Object Already Exists"),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "true")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraFexPAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.allow_test_2", "owner_tag", ""),
				),
			},
		},
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", ""),
				),
			},
			// Update with all config and verify default APIC values
			{
				Config:             testConfigInfraHPortSAllDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "annotation"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", "description_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", "name_alias_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", "owner_key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", "owner_tag_1"),
				),
			},
			// Update with minimum config and verify config is unchanged
			{
				Config:             testConfigInfraHPortSMinDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
				),
			},
			// Update with empty strings config or default value
			{
				Config:             testConfigInfraHPortSResetDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", ""),
				),
			},
			// Import testing
			{
				ResourceName:      "aci_access_port_selector.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children
			{
				Config:             testConfigInfraHPortSChildrenDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name", "test_name"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "port_selector_type", "range"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "description", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotation", "annotation_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.fex_id", "102"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.target_dn", "uni/infra/funcprof/accportgrp-leaf_access_port_policy_group_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.value", "test_value"),
				),
			},
			// Refresh State before import testing to ensure that the state is up to date
			{
				RefreshState:       true,
				ExpectNonEmptyPlan: false,
			},
			// Import testing with children
			{
				ResourceName:      "aci_access_port_selector.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children removed from config
			{
				Config:             testConfigInfraHPortSChildrenRemoveFromConfigDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.#", "2"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotation", "annotation_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.annotations.#", "2"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.tags.#", "2"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.fex_id", "102"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "relation_to_leaf_access_port_policy_group.target_dn", "uni/infra/funcprof/accportgrp-leaf_access_port_policy_group_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.#", "2"),
				),
			},
			// Update with children first child removed
			{
				Config:             testConfigInfraHPortSChildrenRemoveOneDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.#", "1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.#", "1"),
				),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue("aci_access_port_selector.test",
						tfjsonpath.New("relation_to_leaf_access_port_policy_group"),
						knownvalue.MapExact(
							map[string]knownvalue.Check{
								"annotation":  knownvalue.Null(),
								"annotations": knownvalue.Null(),
								"tags":        knownvalue.Null(),
								"fex_id":      knownvalue.Null(),
								"target_dn":   knownvalue.Null(),
							},
						),
					),
				},
			},
			// Update with all children removed
			{
				Config:             testConfigInfraHPortSChildrenRemoveAllDependencyWithInfraFexP,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "annotations.#", "0"),
					resource.TestCheckResourceAttr("aci_access_port_selector.test", "tags.#", "0"),
				),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue("aci_access_port_selector.test",
						tfjsonpath.New("relation_to_leaf_access_port_policy_group"),
						knownvalue.MapExact(
							map[string]knownvalue.Check{
								"annotation":  knownvalue.Null(),
								"annotations": knownvalue.Null(),
								"tags":        knownvalue.Null(),
								"fex_id":      knownvalue.Null(),
								"target_dn":   knownvalue.Null(),
							},
						),
					),
				},
			},
			// Update with legacy attribute config
			{
				Config:             testConfigInfraHPortSLegacyAttributesWithInfraFexP,
				ExpectNonEmptyPlan: false,
			},
		},
		CheckDestroy: testCheckResourceDestroy,
	})
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with legacy attribute config
			{
				Config:             testConfigInfraHPortSLegacyAttributesWithInfraFexP,
				ExpectNonEmptyPlan: false,
			},
		},
		CheckDestroy: testCheckResourceDestroy,
	})
}

const testChildDependencyConfigInfraHPortS = `
resource "aci_leaf_access_port_policy_group" "test_leaf_access_port_policy_group_0"{
  name = "leaf_access_port_policy_group_1"
}
`

const testConfigInfraHPortSMinDependencyWithInfraAccPortPAllowExisting = testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "allow_test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
}
resource "aci_access_port_selector" "allow_test_2" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  depends_on = [aci_access_port_selector.allow_test]
}
`

const testConfigInfraHPortSMinDependencyWithInfraAccPortP = testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
}
`

const testConfigInfraHPortSAllDependencyWithInfraAccPortP = testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotation = "annotation"
  description = "description_1"
  name_alias = "name_alias_1"
  owner_key = "owner_key_1"
  owner_tag = "owner_tag_1"
}
`

const testConfigInfraHPortSResetDependencyWithInfraAccPortP = testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotation = "orchestrator:terraform"
  description = ""
  name_alias = ""
  owner_key = ""
  owner_tag = ""
}
`
const testConfigInfraHPortSChildrenDependencyWithInfraAccPortP = testChildDependencyConfigInfraHPortS + testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotations = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
  relation_to_leaf_access_port_policy_group = {
    annotation = "annotation_1"
    annotations = [
	  {
        key = "key_0"
        value = "value_1"
	  },
	  {
        key = "key_1"
        value = "test_value"
	  },
    ]
    tags = [
	  {
        key = "key_0"
        value = "value_1"
	  },
	  {
        key = "key_1"
        value = "test_value"
	  },
    ]
    fex_id = "102"
    target_dn = aci_leaf_access_port_policy_group.test_leaf_access_port_policy_group_0.id
  }
  tags = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
}
`

const testConfigInfraHPortSChildrenRemoveFromConfigDependencyWithInfraAccPortP = testChildDependencyConfigInfraHPortS + testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
}
`

const testConfigInfraHPortSChildrenRemoveOneDependencyWithInfraAccPortP = testChildDependencyConfigInfraHPortS + testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotations = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
  relation_to_leaf_access_port_policy_group = {}
  tags = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
}
`

const testConfigInfraHPortSChildrenRemoveAllDependencyWithInfraAccPortP = testChildDependencyConfigInfraHPortS + testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_leaf_interface_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotations = []
  relation_to_leaf_access_port_policy_group = {}
  tags = []
}
`

const testConfigInfraHPortSLegacyAttributesWithInfraAccPortP = testChildDependencyConfigInfraHPortS + testConfigInfraAccPortPMin + `
resource "aci_access_port_selector" "test" {
  name = "test_name"
  access_port_selector_type = "range"
  leaf_interface_profile_dn = aci_leaf_interface_profile.test.id
  relation_infra_rs_acc_base_grp = aci_leaf_access_port_policy_group.test_leaf_access_port_policy_group_0.id
}
`

const testConfigInfraHPortSMinDependencyWithInfraFexPAllowExisting = testConfigInfraFexPMin + `
resource "aci_access_port_selector" "allow_test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
}
resource "aci_access_port_selector" "allow_test_2" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  depends_on = [aci_access_port_selector.allow_test]
}
`

const testConfigInfraHPortSMinDependencyWithInfraFexP = testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
}
`

const testConfigInfraHPortSAllDependencyWithInfraFexP = testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotation = "annotation"
  description = "description_1"
  name_alias = "name_alias_1"
  owner_key = "owner_key_1"
  owner_tag = "owner_tag_1"
}
`

const testConfigInfraHPortSResetDependencyWithInfraFexP = testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotation = "orchestrator:terraform"
  description = ""
  name_alias = ""
  owner_key = ""
  owner_tag = ""
}
`
const testConfigInfraHPortSChildrenDependencyWithInfraFexP = testChildDependencyConfigInfraHPortS + testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotations = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
  relation_to_leaf_access_port_policy_group = {
    annotation = "annotation_1"
    annotations = [
	  {
        key = "key_0"
        value = "value_1"
	  },
	  {
        key = "key_1"
        value = "test_value"
	  },
    ]
    tags = [
	  {
        key = "key_0"
        value = "value_1"
	  },
	  {
        key = "key_1"
        value = "test_value"
	  },
    ]
    fex_id = "102"
    target_dn = aci_leaf_access_port_policy_group.test_leaf_access_port_policy_group_0.id
  }
  tags = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
}
`

const testConfigInfraHPortSChildrenRemoveFromConfigDependencyWithInfraFexP = testChildDependencyConfigInfraHPortS + testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
}
`

const testConfigInfraHPortSChildrenRemoveOneDependencyWithInfraFexP = testChildDependencyConfigInfraHPortS + testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotations = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
  relation_to_leaf_access_port_policy_group = {}
  tags = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
}
`

const testConfigInfraHPortSChildrenRemoveAllDependencyWithInfraFexP = testChildDependencyConfigInfraHPortS + testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  parent_dn = aci_fex_profile.test.id
  name = "test_name"
  port_selector_type = "range"
  annotations = []
  relation_to_leaf_access_port_policy_group = {}
  tags = []
}
`

const testConfigInfraHPortSLegacyAttributesWithInfraFexP = testChildDependencyConfigInfraHPortS + testConfigInfraFexPMin + `
resource "aci_access_port_selector" "test" {
  name = "test_name"
  access_port_selector_type = "range"
  leaf_interface_profile_dn = aci_leaf_interface_profile.test.id
  relation_infra_rs_acc_base_grp = aci_leaf_access_port_policy_group.test_leaf_access_port_policy_group_0.id
}
`
