// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccResourceVzRsAnyToProvWithVzAny(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigVzRsAnyToProvMinDependencyWithVzAnyAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "match_criteria", "AtleastOne"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "match_criteria", "AtleastOne"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "priority", "unspecified"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "priority", "unspecified"),
				),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "false")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:      testConfigVzRsAnyToProvMinDependencyWithVzAnyAllowExisting,
				ExpectError: regexp.MustCompile("Object Already Exists"),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "true")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigVzRsAnyToProvMinDependencyWithVzAnyAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "match_criteria", "AtleastOne"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "match_criteria", "AtleastOne"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test", "priority", "unspecified"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.allow_test_2", "priority", "unspecified"),
				),
			},
		},
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "1.0(1e)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigVzRsAnyToProvMinDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "match_criteria", "AtleastOne"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "priority", "unspecified"),
				),
			},
			// Update with all config and verify default APIC values
			{
				Config:             testConfigVzRsAnyToProvAllDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotation", "annotation"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "match_criteria", "All"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "priority", "level1"),
				),
			},
			// Update with minimum config and verify config is unchanged
			{
				Config:             testConfigVzRsAnyToProvMinDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "contract_name", "test_tn_vz_br_cp_name"),
				),
			},
			// Update with empty strings config or default value
			{
				Config:             testConfigVzRsAnyToProvResetDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "match_criteria", "AtleastOne"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "priority", "unspecified"),
				),
			},
			// Import testing
			{
				ResourceName:      "aci_relation_from_any_to_provider_contract.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children
			{
				Config:             testConfigVzRsAnyToProvChildrenDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "match_criteria", "AtleastOne"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "priority", "unspecified"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.1.value", "test_value"),
				),
			},
			// Refresh State before import testing to ensure that the state is up to date
			{
				RefreshState:       true,
				ExpectNonEmptyPlan: false,
			},
			// Import testing with children
			{
				ResourceName:      "aci_relation_from_any_to_provider_contract.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children removed from config
			{
				Config:             testConfigVzRsAnyToProvChildrenRemoveFromConfigDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.#", "2"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.#", "2"),
				),
			},
			// Update with children first child removed
			{
				Config:             testConfigVzRsAnyToProvChildrenRemoveOneDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.#", "1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.#", "1"),
				),
			},
			// Update with all children removed
			{
				Config:             testConfigVzRsAnyToProvChildrenRemoveAllDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "annotations.#", "0"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "tags.#", "0"),
				),
			},
			// Update with minimum config and custom type semantic equivalent values
			{
				Config:             testConfigVzRsAnyToProvCustomTypeDependencyWithVzAny,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "contract_name", "test_tn_vz_br_cp_name"),
					resource.TestCheckResourceAttr("aci_relation_from_any_to_provider_contract.test", "priority", "1"),
				),
			},
		},
		CheckDestroy: testCheckResourceDestroy,
	})
}

const testDependencyConfigVzRsAnyToProv = `
resource "aci_contract" "test_contract_0" {
  tenant_dn = aci_tenant.test.id
  name = "contract_name_1"
}
`

const testConfigVzRsAnyToProvMinDependencyWithVzAnyAllowExisting = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "allow_test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
}
resource "aci_relation_from_any_to_provider_contract" "allow_test_2" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
  depends_on = [aci_relation_from_any_to_provider_contract.allow_test]
}
`

const testConfigVzRsAnyToProvMinDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
}
`

const testConfigVzRsAnyToProvAllDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
  annotation = "annotation"
  match_criteria = "All"
  priority = "level1"
}
`

const testConfigVzRsAnyToProvResetDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
  annotation = "orchestrator:terraform"
  match_criteria = "AtleastOne"
  priority = "unspecified"
}
`
const testConfigVzRsAnyToProvChildrenDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
  annotations = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
  tags = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
}
`

const testConfigVzRsAnyToProvChildrenRemoveFromConfigDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
}
`

const testConfigVzRsAnyToProvChildrenRemoveOneDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
  annotations = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
  tags = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
}
`

const testConfigVzRsAnyToProvChildrenRemoveAllDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
  annotations = []
  tags = []
}
`

const testConfigVzRsAnyToProvCustomTypeDependencyWithVzAny = testDependencyConfigVzRsAnyToProv + testConfigVzAnyMinDependencyWithFvCtx + `
resource "aci_relation_from_any_to_provider_contract" "test" {
  parent_dn = aci_any.test.id
  contract_name = "test_tn_vz_br_cp_name"
  priority = "1"
}
`
