// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/ciscoecosystem/aci-go-client/v2/client"
	"github.com/ciscoecosystem/aci-go-client/v2/container"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &FvnsAddrInstResource{}
var _ resource.ResourceWithImportState = &FvnsAddrInstResource{}

func NewFvnsAddrInstResource() resource.Resource {
	return &FvnsAddrInstResource{}
}

// FvnsAddrInstResource defines the resource implementation.
type FvnsAddrInstResource struct {
	client *client.Client
}

// FvnsAddrInstResourceModel describes the resource data model.
type FvnsAddrInstResourceModel struct {
	Id               types.String `tfsdk:"id"`
	Addr             types.String `tfsdk:"gateway_address"`
	AddrType         types.String `tfsdk:"address_type"`
	Annotation       types.String `tfsdk:"annotation"`
	Descr            types.String `tfsdk:"description"`
	Name             types.String `tfsdk:"name"`
	NameAlias        types.String `tfsdk:"name_alias"`
	OwnerKey         types.String `tfsdk:"owner_key"`
	OwnerTag         types.String `tfsdk:"owner_tag"`
	SkipGwVal        types.String `tfsdk:"skip_gateway_validation"`
	FvnsUcastAddrBlk types.Set    `tfsdk:"ip_address_blocks"`
	TagAnnotation    types.Set    `tfsdk:"annotations"`
	TagTag           types.Set    `tfsdk:"tags"`
}

func getEmptyFvnsAddrInstResourceModel() *FvnsAddrInstResourceModel {
	return &FvnsAddrInstResourceModel{
		Id:         basetypes.NewStringNull(),
		Addr:       basetypes.NewStringNull(),
		AddrType:   basetypes.NewStringNull(),
		Annotation: basetypes.NewStringNull(),
		Descr:      basetypes.NewStringNull(),
		Name:       basetypes.NewStringNull(),
		NameAlias:  basetypes.NewStringNull(),
		OwnerKey:   basetypes.NewStringNull(),
		OwnerTag:   basetypes.NewStringNull(),
		SkipGwVal:  basetypes.NewStringNull(),
		FvnsUcastAddrBlk: types.SetNull(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"annotation":  types.StringType,
				"description": types.StringType,
				"from":        types.StringType,
				"name":        types.StringType,
				"name_alias":  types.StringType,
				"to":          types.StringType,
				"annotations": types.SetType{ElemType: TagAnnotationFvnsUcastAddrBlkFvnsAddrInstType},
				"tags":        types.SetType{ElemType: TagTagFvnsUcastAddrBlkFvnsAddrInstType},
			},
		}),
		TagAnnotation: types.SetNull(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"key":   types.StringType,
				"value": types.StringType,
			},
		}),
		TagTag: types.SetNull(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"key":   types.StringType,
				"value": types.StringType,
			},
		}),
	}
}

// FvnsUcastAddrBlkFvnsAddrInstResourceModel describes the resource data model for the children without relation ships.
type FvnsUcastAddrBlkFvnsAddrInstResourceModel struct {
	Annotation    types.String `tfsdk:"annotation"`
	Descr         types.String `tfsdk:"description"`
	From          types.String `tfsdk:"from"`
	Name          types.String `tfsdk:"name"`
	NameAlias     types.String `tfsdk:"name_alias"`
	To            types.String `tfsdk:"to"`
	TagAnnotation types.Set    `tfsdk:"annotations"`
	TagTag        types.Set    `tfsdk:"tags"`
}

func getEmptyFvnsUcastAddrBlkFvnsAddrInstResourceModel() FvnsUcastAddrBlkFvnsAddrInstResourceModel {
	return FvnsUcastAddrBlkFvnsAddrInstResourceModel{
		Annotation: basetypes.NewStringNull(),
		Descr:      basetypes.NewStringNull(),
		From:       basetypes.NewStringNull(),
		Name:       basetypes.NewStringNull(),
		NameAlias:  basetypes.NewStringNull(),
		To:         basetypes.NewStringNull(),
		TagAnnotation: types.SetNull(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"key":   types.StringType,
				"value": types.StringType,
			},
		}),
		TagTag: types.SetNull(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"key":   types.StringType,
				"value": types.StringType,
			},
		}),
	}
}

var FvnsUcastAddrBlkFvnsAddrInstType = types.ObjectType{
	AttrTypes: map[string]attr.Type{
		"annotation":  types.StringType,
		"description": types.StringType,
		"from":        types.StringType,
		"name":        types.StringType,
		"name_alias":  types.StringType,
		"to":          types.StringType,
		"annotations": types.SetType{ElemType: TagAnnotationFvnsUcastAddrBlkFvnsAddrInstType},
		"tags":        types.SetType{ElemType: TagTagFvnsUcastAddrBlkFvnsAddrInstType},
	},
}

func FvnsUcastAddrBlkFvnsAddrInstSetToSetNullWhenStateIsNullPlanIsUnknownDuringUpdate(ctx context.Context, planValue, stateValue types.Set) basetypes.SetValue {
	//  Function is needed to handle the case that an attribute is not yet supported in a version and gets set to null during read
	var planSetValues, stateSetValues []FvnsUcastAddrBlkFvnsAddrInstResourceModel
	stateValue.ElementsAs(ctx, &stateSetValues, false)
	planValue.ElementsAs(ctx, &planSetValues, false)

	// If the length of the state and plan values are different a change is already detected the loop can be skipped
	if len(stateSetValues) == len(planSetValues) {
		for index, stateValue := range stateSetValues {
			nullInStateFound := false
			if stateValue.Annotation.IsNull() {
				nullInStateFound = true
				planSetValues[index].Annotation = basetypes.NewStringNull()
			}
			if stateValue.Descr.IsNull() {
				nullInStateFound = true
				planSetValues[index].Descr = basetypes.NewStringNull()
			}
			if stateValue.From.IsNull() {
				nullInStateFound = true
				planSetValues[index].From = basetypes.NewStringNull()
			}
			if stateValue.Name.IsNull() {
				nullInStateFound = true
				planSetValues[index].Name = basetypes.NewStringNull()
			}
			if stateValue.NameAlias.IsNull() {
				nullInStateFound = true
				planSetValues[index].NameAlias = basetypes.NewStringNull()
			}
			if stateValue.To.IsNull() {
				nullInStateFound = true
				planSetValues[index].To = basetypes.NewStringNull()
			}
			if !nullInStateFound {
				// when there are no null fields we can conclude the version supports all attributes in set
				break
			}
		}
	}
	planSet, _ := types.SetValueFrom(ctx, FvnsUcastAddrBlkFvnsAddrInstType, planSetValues)
	return planSet

}

// TagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel describes the resource data model for the children without relation ships.
type TagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func getEmptyTagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel() TagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel {
	return TagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel{
		Key:   basetypes.NewStringNull(),
		Value: basetypes.NewStringNull(),
	}
}

var TagAnnotationFvnsUcastAddrBlkFvnsAddrInstType = types.ObjectType{
	AttrTypes: map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	},
}

// TagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel describes the resource data model for the children without relation ships.
type TagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func getEmptyTagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel() TagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel {
	return TagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel{
		Key:   basetypes.NewStringNull(),
		Value: basetypes.NewStringNull(),
	}
}

var TagTagFvnsUcastAddrBlkFvnsAddrInstType = types.ObjectType{
	AttrTypes: map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	},
}

// TagAnnotationFvnsAddrInstResourceModel describes the resource data model for the children without relation ships.
type TagAnnotationFvnsAddrInstResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func getEmptyTagAnnotationFvnsAddrInstResourceModel() TagAnnotationFvnsAddrInstResourceModel {
	return TagAnnotationFvnsAddrInstResourceModel{
		Key:   basetypes.NewStringNull(),
		Value: basetypes.NewStringNull(),
	}
}

var TagAnnotationFvnsAddrInstType = types.ObjectType{
	AttrTypes: map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	},
}

// TagTagFvnsAddrInstResourceModel describes the resource data model for the children without relation ships.
type TagTagFvnsAddrInstResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func getEmptyTagTagFvnsAddrInstResourceModel() TagTagFvnsAddrInstResourceModel {
	return TagTagFvnsAddrInstResourceModel{
		Key:   basetypes.NewStringNull(),
		Value: basetypes.NewStringNull(),
	}
}

var TagTagFvnsAddrInstType = types.ObjectType{
	AttrTypes: map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	},
}

type FvnsAddrInstIdentifier struct {
	Name types.String
}

func (r *FvnsAddrInstResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if !req.Plan.Raw.IsNull() {
		var planData, stateData *FvnsAddrInstResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &planData)...)
		resp.Diagnostics.Append(req.State.Get(ctx, &stateData)...)

		if resp.Diagnostics.HasError() {
			return
		}

		if (planData.Id.IsUnknown() || planData.Id.IsNull()) && !planData.Name.IsUnknown() {
			setFvnsAddrInstId(ctx, planData)
		}

		if stateData == nil && !globalAllowExistingOnCreate && !planData.Id.IsUnknown() && !planData.Id.IsNull() {
			CheckDn(ctx, &resp.Diagnostics, r.client, "fvnsAddrInst", planData.Id.ValueString())
			if resp.Diagnostics.HasError() {
				return
			}
		}

		resp.Diagnostics.Append(resp.Plan.Set(ctx, &planData)...)
	}
}

func (r *FvnsAddrInstResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	tflog.Debug(ctx, "Start metadata of resource: aci_ip_address_pool")
	resp.TypeName = req.ProviderTypeName + "_ip_address_pool"
	tflog.Debug(ctx, "End metadata of resource: aci_ip_address_pool")
}

func (r *FvnsAddrInstResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	tflog.Debug(ctx, "Start schema of resource: aci_ip_address_pool")
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "The ip_address_pool resource for the 'fvnsAddrInst' class",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The distinguished name (DN) of the IP Address Pool object.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
				},
			},
			"gateway_address": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `The gateway address of the IP Address Pool object.`,
			},
			"address_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("regular", "vip_range"),
				},
				MarkdownDescription: `The gateway address type of the IP Address Pool object.`,
			},
			"annotation": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				Default:             stringdefault.StaticString(globalAnnotation),
				MarkdownDescription: `The annotation of the IP Address Pool object.`,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `The description of the IP Address Pool object.`,
			},
			"name": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
					stringplanmodifier.RequiresReplace(),
				},
				MarkdownDescription: `The name of the IP Address Pool object.`,
			},
			"name_alias": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `The name alias of the IP Address Pool object.`,
			},
			"owner_key": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `The key for enabling clients to own their data for entity correlation.`,
			},
			"owner_tag": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `A tag for enabling clients to add their own data. For example, to indicate who created this object.`,
			},
			"skip_gateway_validation": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("no", "yes"),
				},
				MarkdownDescription: `Skip gateway validation for the IP Address Pool object.`,
			},
			"ip_address_blocks": schema.SetNestedAttribute{
				MarkdownDescription: `Defines the first and last unicast IP addresses in the namespace block.`,
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseNonNullStateForUnknown(),
					SetToSetNullWhenStateIsNullPlanIsUnknownDuringUpdate(FvnsUcastAddrBlkFvnsAddrInstSetToSetNullWhenStateIsNullPlanIsUnknownDuringUpdate),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"annotation": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The annotation of the IP Address Block object.`,
						},
						"description": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The description of the IP Address Block object.`,
						},
						"from": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The first unicast address in the address block.`,
						},
						"name": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The name of the IP Address Block object.`,
						},
						"name_alias": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The name alias of the IP Address Block object.`,
						},
						"to": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The last unicast address in the address block.`,
						},
						"annotations": schema.SetNestedAttribute{
							MarkdownDescription: ``,
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.Set{
								setplanmodifier.UseNonNullStateForUnknown(),
							},
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseNonNullStateForUnknown(),
										},
										MarkdownDescription: `The key used to uniquely identify this configuration object.`,
									},
									"value": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseNonNullStateForUnknown(),
										},
										MarkdownDescription: `The value of the property.`,
									},
								},
							},
						},
						"tags": schema.SetNestedAttribute{
							MarkdownDescription: ``,
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.Set{
								setplanmodifier.UseNonNullStateForUnknown(),
							},
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseNonNullStateForUnknown(),
										},
										MarkdownDescription: `The key used to uniquely identify this configuration object.`,
									},
									"value": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseNonNullStateForUnknown(),
										},
										MarkdownDescription: `The value of the property.`,
									},
								},
							},
						},
					},
				},
			},
			"annotations": schema.SetNestedAttribute{
				MarkdownDescription: ``,
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseNonNullStateForUnknown(),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The key used to uniquely identify this configuration object.`,
						},
						"value": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The value of the property.`,
						},
					},
				},
			},
			"tags": schema.SetNestedAttribute{
				MarkdownDescription: ``,
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseNonNullStateForUnknown(),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The key used to uniquely identify this configuration object.`,
						},
						"value": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseNonNullStateForUnknown(),
							},
							MarkdownDescription: `The value of the property.`,
						},
					},
				},
			},
		},
	}
	tflog.Debug(ctx, "End schema of resource: aci_ip_address_pool")
}

func (r *FvnsAddrInstResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	tflog.Debug(ctx, "Start configure of resource: aci_ip_address_pool")
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
	tflog.Debug(ctx, "End configure of resource: aci_ip_address_pool")
}

func (r *FvnsAddrInstResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Debug(ctx, "Start create of resource: aci_ip_address_pool")
	// On create retrieve information on current state prior to making any changes in order to determine child delete operations
	var stateData *FvnsAddrInstResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &stateData)...)
	if stateData.Id.IsUnknown() || stateData.Id.IsNull() {
		setFvnsAddrInstId(ctx, stateData)
	}
	getAndSetFvnsAddrInstAttributes(ctx, &resp.Diagnostics, r.client, stateData)
	if !globalAllowExistingOnCreate && !stateData.Id.IsNull() {
		resp.Diagnostics.AddError(
			"Object Already Exists",
			fmt.Sprintf("The fvnsAddrInst object with DN '%s' already exists.", stateData.Id.ValueString()),
		)
		return
	}

	var data *FvnsAddrInstResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if data.Id.IsUnknown() || data.Id.IsNull() {
		setFvnsAddrInstId(ctx, data)
	}

	tflog.Debug(ctx, fmt.Sprintf("Create of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))

	var fvnsUcastAddrBlkPlan, fvnsUcastAddrBlkState []FvnsUcastAddrBlkFvnsAddrInstResourceModel
	data.FvnsUcastAddrBlk.ElementsAs(ctx, &fvnsUcastAddrBlkPlan, false)
	stateData.FvnsUcastAddrBlk.ElementsAs(ctx, &fvnsUcastAddrBlkState, false)
	var tagAnnotationPlan, tagAnnotationState []TagAnnotationFvnsAddrInstResourceModel
	data.TagAnnotation.ElementsAs(ctx, &tagAnnotationPlan, false)
	stateData.TagAnnotation.ElementsAs(ctx, &tagAnnotationState, false)
	var tagTagPlan, tagTagState []TagTagFvnsAddrInstResourceModel
	data.TagTag.ElementsAs(ctx, &tagTagPlan, false)
	stateData.TagTag.ElementsAs(ctx, &tagTagState, false)
	jsonPayload := getFvnsAddrInstCreateJsonPayload(ctx, &resp.Diagnostics, true, data, fvnsUcastAddrBlkPlan, fvnsUcastAddrBlkState, tagAnnotationPlan, tagAnnotationState, tagTagPlan, tagTagState)

	if resp.Diagnostics.HasError() {
		return
	}

	DoRestRequest(ctx, &resp.Diagnostics, r.client, fmt.Sprintf("api/mo/%s.json", data.Id.ValueString()), "POST", jsonPayload)

	if resp.Diagnostics.HasError() {
		return
	}

	getAndSetFvnsAddrInstAttributes(ctx, &resp.Diagnostics, r.client, data)

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	tflog.Debug(ctx, fmt.Sprintf("End create of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))
}

func (r *FvnsAddrInstResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	tflog.Debug(ctx, "Start read of resource: aci_ip_address_pool")
	var data *FvnsAddrInstResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Read of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))

	getAndSetFvnsAddrInstAttributes(ctx, &resp.Diagnostics, r.client, data)

	// Save updated data into Terraform state
	if data.Id.IsNull() {
		var emptyData *FvnsAddrInstResourceModel
		resp.Diagnostics.Append(resp.State.Set(ctx, &emptyData)...)
	} else {
		resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	}

	tflog.Debug(ctx, fmt.Sprintf("End read of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))
}

func (r *FvnsAddrInstResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	tflog.Debug(ctx, "Start update of resource: aci_ip_address_pool")
	var data *FvnsAddrInstResourceModel
	var stateData *FvnsAddrInstResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &stateData)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Update of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))

	var fvnsUcastAddrBlkPlan, fvnsUcastAddrBlkState []FvnsUcastAddrBlkFvnsAddrInstResourceModel
	data.FvnsUcastAddrBlk.ElementsAs(ctx, &fvnsUcastAddrBlkPlan, false)
	stateData.FvnsUcastAddrBlk.ElementsAs(ctx, &fvnsUcastAddrBlkState, false)
	var tagAnnotationPlan, tagAnnotationState []TagAnnotationFvnsAddrInstResourceModel
	data.TagAnnotation.ElementsAs(ctx, &tagAnnotationPlan, false)
	stateData.TagAnnotation.ElementsAs(ctx, &tagAnnotationState, false)
	var tagTagPlan, tagTagState []TagTagFvnsAddrInstResourceModel
	data.TagTag.ElementsAs(ctx, &tagTagPlan, false)
	stateData.TagTag.ElementsAs(ctx, &tagTagState, false)
	jsonPayload := getFvnsAddrInstCreateJsonPayload(ctx, &resp.Diagnostics, false, data, fvnsUcastAddrBlkPlan, fvnsUcastAddrBlkState, tagAnnotationPlan, tagAnnotationState, tagTagPlan, tagTagState)

	if resp.Diagnostics.HasError() {
		return
	}

	DoRestRequest(ctx, &resp.Diagnostics, r.client, fmt.Sprintf("api/mo/%s.json", data.Id.ValueString()), "POST", jsonPayload)

	if resp.Diagnostics.HasError() {
		return
	}

	getAndSetFvnsAddrInstAttributes(ctx, &resp.Diagnostics, r.client, data)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	tflog.Debug(ctx, fmt.Sprintf("End update of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))
}

func (r *FvnsAddrInstResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Debug(ctx, "Start delete of resource: aci_ip_address_pool")
	var data *FvnsAddrInstResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Delete of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))
	jsonPayload := GetDeleteJsonPayload(ctx, &resp.Diagnostics, "fvnsAddrInst", data.Id.ValueString())
	if resp.Diagnostics.HasError() {
		return
	}
	DoRestRequest(ctx, &resp.Diagnostics, r.client, fmt.Sprintf("api/mo/%s.json", data.Id.ValueString()), "POST", jsonPayload)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, fmt.Sprintf("End delete of resource aci_ip_address_pool with id '%s'", data.Id.ValueString()))
}

func (r *FvnsAddrInstResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Start import state of resource: aci_ip_address_pool")
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)

	var stateData *FvnsAddrInstResourceModel
	resp.Diagnostics.Append(resp.State.Get(ctx, &stateData)...)
	tflog.Debug(ctx, fmt.Sprintf("Import state of resource aci_ip_address_pool with id '%s'", stateData.Id.ValueString()))

	tflog.Debug(ctx, "End import of state resource: aci_ip_address_pool")
}

func getAndSetFvnsAddrInstAttributes(ctx context.Context, diags *diag.Diagnostics, client *client.Client, data *FvnsAddrInstResourceModel) {
	requestData := DoRestRequest(ctx, diags, client, fmt.Sprintf("api/mo/%s.json?rsp-subtree=full&rsp-subtree-class=%s", data.Id.ValueString(), "fvnsAddrInst,fvnsUcastAddrBlk,tagAnnotation,tagTag,tagAnnotation,tagTag"), "GET", nil)

	readData := getEmptyFvnsAddrInstResourceModel()

	if diags.HasError() {
		return
	}
	if requestData.Search("imdata").Search("fvnsAddrInst").Data() != nil {
		classReadInfo := requestData.Search("imdata").Search("fvnsAddrInst").Data().([]interface{})
		if len(classReadInfo) == 1 {
			attributes := classReadInfo[0].(map[string]interface{})["attributes"].(map[string]interface{})
			for attributeName, attributeValue := range attributes {
				if attributeName == "dn" {
					readData.Id = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "addr" {
					readData.Addr = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "addrType" {
					readData.AddrType = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "annotation" {
					readData.Annotation = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "descr" {
					readData.Descr = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "name" {
					readData.Name = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "nameAlias" {
					readData.NameAlias = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "ownerKey" {
					readData.OwnerKey = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "ownerTag" {
					readData.OwnerTag = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "skipGwVal" {
					readData.SkipGwVal = basetypes.NewStringValue(attributeValue.(string))
				}
			}
			FvnsUcastAddrBlkFvnsAddrInstList := make([]FvnsUcastAddrBlkFvnsAddrInstResourceModel, 0)
			TagAnnotationFvnsAddrInstList := make([]TagAnnotationFvnsAddrInstResourceModel, 0)
			TagTagFvnsAddrInstList := make([]TagTagFvnsAddrInstResourceModel, 0)
			_, ok := classReadInfo[0].(map[string]interface{})["children"]
			if ok {
				children := classReadInfo[0].(map[string]interface{})["children"].([]interface{})
				for _, child := range children {
					for childClassName, childClassDetails := range child.(map[string]interface{}) {
						childAttributes := childClassDetails.(map[string]interface{})["attributes"].(map[string]interface{})
						if childClassName == "fvnsUcastAddrBlk" {
							FvnsUcastAddrBlkFvnsAddrInst := getEmptyFvnsUcastAddrBlkFvnsAddrInstResourceModel()
							for childAttributeName, childAttributeValue := range childAttributes {
								if childAttributeName == "annotation" {
									FvnsUcastAddrBlkFvnsAddrInst.Annotation = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "descr" {
									FvnsUcastAddrBlkFvnsAddrInst.Descr = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "from" {
									FvnsUcastAddrBlkFvnsAddrInst.From = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "name" {
									FvnsUcastAddrBlkFvnsAddrInst.Name = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "nameAlias" {
									FvnsUcastAddrBlkFvnsAddrInst.NameAlias = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "to" {
									FvnsUcastAddrBlkFvnsAddrInst.To = basetypes.NewStringValue(childAttributeValue.(string))
								}

							}
							TagAnnotationFvnsUcastAddrBlkFvnsAddrInstList := make([]TagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel, 0)
							TagTagFvnsUcastAddrBlkFvnsAddrInstList := make([]TagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel, 0)
							childrenOfFvnsUcastAddrBlkFvnsAddrInst, childrenOfFvnsUcastAddrBlkFvnsAddrInstExist := childClassDetails.(map[string]interface{})["children"]
							if childrenOfFvnsUcastAddrBlkFvnsAddrInstExist {
								for _, childFvnsUcastAddrBlkFvnsAddrInst := range childrenOfFvnsUcastAddrBlkFvnsAddrInst.([]interface{}) {
									for childClassNameFvnsUcastAddrBlkFvnsAddrInst, childClassDetailsFvnsUcastAddrBlkFvnsAddrInst := range childFvnsUcastAddrBlkFvnsAddrInst.(map[string]interface{}) {
										if childClassNameFvnsUcastAddrBlkFvnsAddrInst == "tagAnnotation" {
											TagAnnotationFvnsUcastAddrBlkFvnsAddrInst := getEmptyTagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel()
											tagAnnotationchildAttributeValue := childClassDetailsFvnsUcastAddrBlkFvnsAddrInst.(map[string]interface{})["attributes"].(map[string]interface{})
											for childAttributeName, childAttributeValue := range tagAnnotationchildAttributeValue {
												if childAttributeName == "key" {
													TagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Key = basetypes.NewStringValue(childAttributeValue.(string))
												}
												if childAttributeName == "value" {
													TagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Value = basetypes.NewStringValue(childAttributeValue.(string))
												}
											}
											TagAnnotationFvnsUcastAddrBlkFvnsAddrInstList = append(TagAnnotationFvnsUcastAddrBlkFvnsAddrInstList, TagAnnotationFvnsUcastAddrBlkFvnsAddrInst)
										}
										if childClassNameFvnsUcastAddrBlkFvnsAddrInst == "tagTag" {
											TagTagFvnsUcastAddrBlkFvnsAddrInst := getEmptyTagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel()
											tagTagchildAttributeValue := childClassDetailsFvnsUcastAddrBlkFvnsAddrInst.(map[string]interface{})["attributes"].(map[string]interface{})
											for childAttributeName, childAttributeValue := range tagTagchildAttributeValue {
												if childAttributeName == "key" {
													TagTagFvnsUcastAddrBlkFvnsAddrInst.Key = basetypes.NewStringValue(childAttributeValue.(string))
												}
												if childAttributeName == "value" {
													TagTagFvnsUcastAddrBlkFvnsAddrInst.Value = basetypes.NewStringValue(childAttributeValue.(string))
												}
											}
											TagTagFvnsUcastAddrBlkFvnsAddrInstList = append(TagTagFvnsUcastAddrBlkFvnsAddrInstList, TagTagFvnsUcastAddrBlkFvnsAddrInst)
										}
									}
								}
							}
							TagAnnotationFvnsUcastAddrBlkFvnsAddrInstSet, _ := types.SetValueFrom(ctx, TagAnnotationFvnsUcastAddrBlkFvnsAddrInstType, TagAnnotationFvnsUcastAddrBlkFvnsAddrInstList)
							FvnsUcastAddrBlkFvnsAddrInst.TagAnnotation = TagAnnotationFvnsUcastAddrBlkFvnsAddrInstSet
							TagTagFvnsUcastAddrBlkFvnsAddrInstSet, _ := types.SetValueFrom(ctx, TagTagFvnsUcastAddrBlkFvnsAddrInstType, TagTagFvnsUcastAddrBlkFvnsAddrInstList)
							FvnsUcastAddrBlkFvnsAddrInst.TagTag = TagTagFvnsUcastAddrBlkFvnsAddrInstSet
							FvnsUcastAddrBlkFvnsAddrInstList = append(FvnsUcastAddrBlkFvnsAddrInstList, FvnsUcastAddrBlkFvnsAddrInst)
						}
						if childClassName == "tagAnnotation" {
							TagAnnotationFvnsAddrInst := getEmptyTagAnnotationFvnsAddrInstResourceModel()
							for childAttributeName, childAttributeValue := range childAttributes {
								if childAttributeName == "key" {
									TagAnnotationFvnsAddrInst.Key = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "value" {
									TagAnnotationFvnsAddrInst.Value = basetypes.NewStringValue(childAttributeValue.(string))
								}

							}
							TagAnnotationFvnsAddrInstList = append(TagAnnotationFvnsAddrInstList, TagAnnotationFvnsAddrInst)
						}
						if childClassName == "tagTag" {
							TagTagFvnsAddrInst := getEmptyTagTagFvnsAddrInstResourceModel()
							for childAttributeName, childAttributeValue := range childAttributes {
								if childAttributeName == "key" {
									TagTagFvnsAddrInst.Key = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "value" {
									TagTagFvnsAddrInst.Value = basetypes.NewStringValue(childAttributeValue.(string))
								}

							}
							TagTagFvnsAddrInstList = append(TagTagFvnsAddrInstList, TagTagFvnsAddrInst)
						}
					}
				}
			}
			fvnsUcastAddrBlkSet, _ := types.SetValueFrom(ctx, readData.FvnsUcastAddrBlk.ElementType(ctx), FvnsUcastAddrBlkFvnsAddrInstList)
			readData.FvnsUcastAddrBlk = fvnsUcastAddrBlkSet
			tagAnnotationSet, _ := types.SetValueFrom(ctx, readData.TagAnnotation.ElementType(ctx), TagAnnotationFvnsAddrInstList)
			readData.TagAnnotation = tagAnnotationSet
			tagTagSet, _ := types.SetValueFrom(ctx, readData.TagTag.ElementType(ctx), TagTagFvnsAddrInstList)
			readData.TagTag = tagTagSet
		} else {
			diags.AddError(
				"too many results in response",
				fmt.Sprintf("%v matches returned for class 'fvnsAddrInst'. Please report this issue to the provider developers.", len(classReadInfo)),
			)
		}
	} else {
		readData.Id = basetypes.NewStringNull()
	}
	*data = *readData
}

func getFvnsAddrInstRn(ctx context.Context, data *FvnsAddrInstResourceModel) string {
	return fmt.Sprintf("tn-mgmt/addrinst-%s", data.Name.ValueString())
}

func setFvnsAddrInstId(ctx context.Context, data *FvnsAddrInstResourceModel) {
	rn := getFvnsAddrInstRn(ctx, data)
	data.Id = types.StringValue(fmt.Sprintf("%s/%s", strings.Split([]string{"uni/tn-{name}/addrinst-{name}"}[0], "/")[0], rn))
}

func getFvnsAddrInstFvnsUcastAddrBlkChildPayloads(ctx context.Context, diags *diag.Diagnostics, data *FvnsAddrInstResourceModel, fvnsUcastAddrBlkFvnsAddrInstPlan, fvnsUcastAddrBlkFvnsAddrInstState []FvnsUcastAddrBlkFvnsAddrInstResourceModel) []map[string]interface{} {
	childPayloads := []map[string]interface{}{}
	if !data.FvnsUcastAddrBlk.IsNull() && !data.FvnsUcastAddrBlk.IsUnknown() {
		fvnsUcastAddrBlkIdentifiers := []FvnsUcastAddrBlkIdentifier{}
		for _, fvnsUcastAddrBlkFvnsAddrInst := range fvnsUcastAddrBlkFvnsAddrInstPlan {
			FvnsUcastAddrBlkFvnsAddrInstChildren := make([]map[string]interface{}, 0)
			childMap := NewAciObject()
			if !fvnsUcastAddrBlkFvnsAddrInst.Annotation.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.Annotation.IsUnknown() {
				childMap.Attributes["annotation"] = fvnsUcastAddrBlkFvnsAddrInst.Annotation.ValueString()
			} else {
				childMap.Attributes["annotation"] = globalAnnotation
			}
			if !fvnsUcastAddrBlkFvnsAddrInst.Descr.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.Descr.IsUnknown() {
				childMap.Attributes["descr"] = fvnsUcastAddrBlkFvnsAddrInst.Descr.ValueString()
			}
			if !fvnsUcastAddrBlkFvnsAddrInst.From.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.From.IsUnknown() {
				childMap.Attributes["from"] = fvnsUcastAddrBlkFvnsAddrInst.From.ValueString()
			}
			if !fvnsUcastAddrBlkFvnsAddrInst.Name.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.Name.IsUnknown() {
				childMap.Attributes["name"] = fvnsUcastAddrBlkFvnsAddrInst.Name.ValueString()
			}
			if !fvnsUcastAddrBlkFvnsAddrInst.NameAlias.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.NameAlias.IsUnknown() {
				childMap.Attributes["nameAlias"] = fvnsUcastAddrBlkFvnsAddrInst.NameAlias.ValueString()
			}
			if !fvnsUcastAddrBlkFvnsAddrInst.To.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.To.IsUnknown() {
				childMap.Attributes["to"] = fvnsUcastAddrBlkFvnsAddrInst.To.ValueString()
			}

			var tagAnnotationFvnsUcastAddrBlkFvnsAddrInstPlan, tagAnnotationFvnsUcastAddrBlkFvnsAddrInstState []TagAnnotationFvnsUcastAddrBlkFvnsAddrInstResourceModel
			fvnsUcastAddrBlkFvnsAddrInst.TagAnnotation.ElementsAs(ctx, &tagAnnotationFvnsUcastAddrBlkFvnsAddrInstPlan, false)
			for _, tagAnnotationFvnsUcastAddrBlkFvnsAddrInststate := range fvnsUcastAddrBlkFvnsAddrInstState {
				tagAnnotationFvnsUcastAddrBlkFvnsAddrInststate.TagAnnotation.ElementsAs(ctx, &tagAnnotationFvnsUcastAddrBlkFvnsAddrInstState, false)
			}
			if !fvnsUcastAddrBlkFvnsAddrInst.TagAnnotation.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.TagAnnotation.IsUnknown() {
				tagAnnotationIdentifiers := []TagAnnotationIdentifier{}
				for _, tagAnnotationFvnsUcastAddrBlkFvnsAddrInst := range tagAnnotationFvnsUcastAddrBlkFvnsAddrInstPlan {
					tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMap := NewAciObject()
					if !tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Key.IsNull() && !tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Key.IsUnknown() {
						tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMap.Attributes["key"] = tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Key.ValueString()
					}
					if !tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Value.IsNull() && !tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Value.IsUnknown() {
						tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMap.Attributes["value"] = tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Value.ValueString()
					}
					FvnsUcastAddrBlkFvnsAddrInstChildren = append(FvnsUcastAddrBlkFvnsAddrInstChildren, map[string]interface{}{"tagAnnotation": tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMap})
					tagAnnotationIdentifier := TagAnnotationIdentifier{}
					tagAnnotationIdentifier.Key = tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Key
					tagAnnotationIdentifiers = append(tagAnnotationIdentifiers, tagAnnotationIdentifier)
				}
				for _, tagAnnotationFvnsUcastAddrBlkFvnsAddrInst := range tagAnnotationFvnsUcastAddrBlkFvnsAddrInstState {
					delete := true
					for _, tagAnnotationIdentifier := range tagAnnotationIdentifiers {
						if tagAnnotationIdentifier.Key == tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Key {
							delete = false
							break
						}
					}
					if delete {
						tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete := NewAciObject()
						tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete.Attributes["status"] = "deleted"
						tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete.Attributes["key"] = tagAnnotationFvnsUcastAddrBlkFvnsAddrInst.Key.ValueString()
						FvnsUcastAddrBlkFvnsAddrInstChildren = append(FvnsUcastAddrBlkFvnsAddrInstChildren, map[string]interface{}{"tagAnnotation": tagAnnotationFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete})
					}
				}
			}

			var tagTagFvnsUcastAddrBlkFvnsAddrInstPlan, tagTagFvnsUcastAddrBlkFvnsAddrInstState []TagTagFvnsUcastAddrBlkFvnsAddrInstResourceModel
			fvnsUcastAddrBlkFvnsAddrInst.TagTag.ElementsAs(ctx, &tagTagFvnsUcastAddrBlkFvnsAddrInstPlan, false)
			for _, tagTagFvnsUcastAddrBlkFvnsAddrInststate := range fvnsUcastAddrBlkFvnsAddrInstState {
				tagTagFvnsUcastAddrBlkFvnsAddrInststate.TagTag.ElementsAs(ctx, &tagTagFvnsUcastAddrBlkFvnsAddrInstState, false)
			}
			if !fvnsUcastAddrBlkFvnsAddrInst.TagTag.IsNull() && !fvnsUcastAddrBlkFvnsAddrInst.TagTag.IsUnknown() {
				tagTagIdentifiers := []TagTagIdentifier{}
				for _, tagTagFvnsUcastAddrBlkFvnsAddrInst := range tagTagFvnsUcastAddrBlkFvnsAddrInstPlan {
					tagTagFvnsUcastAddrBlkFvnsAddrInstChildMap := NewAciObject()
					if !tagTagFvnsUcastAddrBlkFvnsAddrInst.Key.IsNull() && !tagTagFvnsUcastAddrBlkFvnsAddrInst.Key.IsUnknown() {
						tagTagFvnsUcastAddrBlkFvnsAddrInstChildMap.Attributes["key"] = tagTagFvnsUcastAddrBlkFvnsAddrInst.Key.ValueString()
					}
					if !tagTagFvnsUcastAddrBlkFvnsAddrInst.Value.IsNull() && !tagTagFvnsUcastAddrBlkFvnsAddrInst.Value.IsUnknown() {
						tagTagFvnsUcastAddrBlkFvnsAddrInstChildMap.Attributes["value"] = tagTagFvnsUcastAddrBlkFvnsAddrInst.Value.ValueString()
					}
					FvnsUcastAddrBlkFvnsAddrInstChildren = append(FvnsUcastAddrBlkFvnsAddrInstChildren, map[string]interface{}{"tagTag": tagTagFvnsUcastAddrBlkFvnsAddrInstChildMap})
					tagTagIdentifier := TagTagIdentifier{}
					tagTagIdentifier.Key = tagTagFvnsUcastAddrBlkFvnsAddrInst.Key
					tagTagIdentifiers = append(tagTagIdentifiers, tagTagIdentifier)
				}
				for _, tagTagFvnsUcastAddrBlkFvnsAddrInst := range tagTagFvnsUcastAddrBlkFvnsAddrInstState {
					delete := true
					for _, tagTagIdentifier := range tagTagIdentifiers {
						if tagTagIdentifier.Key == tagTagFvnsUcastAddrBlkFvnsAddrInst.Key {
							delete = false
							break
						}
					}
					if delete {
						tagTagFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete := NewAciObject()
						tagTagFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete.Attributes["status"] = "deleted"
						tagTagFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete.Attributes["key"] = tagTagFvnsUcastAddrBlkFvnsAddrInst.Key.ValueString()
						FvnsUcastAddrBlkFvnsAddrInstChildren = append(FvnsUcastAddrBlkFvnsAddrInstChildren, map[string]interface{}{"tagTag": tagTagFvnsUcastAddrBlkFvnsAddrInstChildMapForDelete})
					}
				}
			}
			childMap.Children = FvnsUcastAddrBlkFvnsAddrInstChildren
			childPayloads = append(childPayloads, map[string]interface{}{"fvnsUcastAddrBlk": childMap})
			fvnsUcastAddrBlkIdentifier := FvnsUcastAddrBlkIdentifier{}
			fvnsUcastAddrBlkIdentifier.From = fvnsUcastAddrBlkFvnsAddrInst.From
			fvnsUcastAddrBlkIdentifier.To = fvnsUcastAddrBlkFvnsAddrInst.To
			fvnsUcastAddrBlkIdentifiers = append(fvnsUcastAddrBlkIdentifiers, fvnsUcastAddrBlkIdentifier)
		}
		for _, fvnsUcastAddrBlk := range fvnsUcastAddrBlkFvnsAddrInstState {
			delete := true
			for _, fvnsUcastAddrBlkIdentifier := range fvnsUcastAddrBlkIdentifiers {
				if fvnsUcastAddrBlkIdentifier.From == fvnsUcastAddrBlk.From &&
					fvnsUcastAddrBlkIdentifier.To == fvnsUcastAddrBlk.To {
					delete = false
					break
				}
			}
			if delete {
				fvnsUcastAddrBlkChildMapForDelete := NewAciObject()
				fvnsUcastAddrBlkChildMapForDelete.Attributes["status"] = "deleted"
				fvnsUcastAddrBlkChildMapForDelete.Attributes["from"] = fvnsUcastAddrBlk.From.ValueString()
				fvnsUcastAddrBlkChildMapForDelete.Attributes["to"] = fvnsUcastAddrBlk.To.ValueString()
				childPayloads = append(childPayloads, map[string]interface{}{"fvnsUcastAddrBlk": fvnsUcastAddrBlkChildMapForDelete})
			}
		}
	} else {
		data.FvnsUcastAddrBlk = types.SetNull(data.FvnsUcastAddrBlk.ElementType(ctx))
	}

	return childPayloads
}

func getFvnsAddrInstTagAnnotationChildPayloads(ctx context.Context, diags *diag.Diagnostics, data *FvnsAddrInstResourceModel, tagAnnotationFvnsAddrInstPlan, tagAnnotationFvnsAddrInstState []TagAnnotationFvnsAddrInstResourceModel) []map[string]interface{} {
	childPayloads := []map[string]interface{}{}
	if !data.TagAnnotation.IsNull() && !data.TagAnnotation.IsUnknown() {
		tagAnnotationIdentifiers := []TagAnnotationIdentifier{}
		for _, tagAnnotationFvnsAddrInst := range tagAnnotationFvnsAddrInstPlan {
			childMap := NewAciObject()
			if !tagAnnotationFvnsAddrInst.Key.IsNull() && !tagAnnotationFvnsAddrInst.Key.IsUnknown() {
				childMap.Attributes["key"] = tagAnnotationFvnsAddrInst.Key.ValueString()
			}
			if !tagAnnotationFvnsAddrInst.Value.IsNull() && !tagAnnotationFvnsAddrInst.Value.IsUnknown() {
				childMap.Attributes["value"] = tagAnnotationFvnsAddrInst.Value.ValueString()
			}
			childPayloads = append(childPayloads, map[string]interface{}{"tagAnnotation": childMap})
			tagAnnotationIdentifier := TagAnnotationIdentifier{}
			tagAnnotationIdentifier.Key = tagAnnotationFvnsAddrInst.Key
			tagAnnotationIdentifiers = append(tagAnnotationIdentifiers, tagAnnotationIdentifier)
		}
		for _, tagAnnotation := range tagAnnotationFvnsAddrInstState {
			delete := true
			for _, tagAnnotationIdentifier := range tagAnnotationIdentifiers {
				if tagAnnotationIdentifier.Key == tagAnnotation.Key {
					delete = false
					break
				}
			}
			if delete {
				tagAnnotationChildMapForDelete := NewAciObject()
				tagAnnotationChildMapForDelete.Attributes["status"] = "deleted"
				tagAnnotationChildMapForDelete.Attributes["key"] = tagAnnotation.Key.ValueString()
				childPayloads = append(childPayloads, map[string]interface{}{"tagAnnotation": tagAnnotationChildMapForDelete})
			}
		}
	} else {
		data.TagAnnotation = types.SetNull(data.TagAnnotation.ElementType(ctx))
	}

	return childPayloads
}

func getFvnsAddrInstTagTagChildPayloads(ctx context.Context, diags *diag.Diagnostics, data *FvnsAddrInstResourceModel, tagTagFvnsAddrInstPlan, tagTagFvnsAddrInstState []TagTagFvnsAddrInstResourceModel) []map[string]interface{} {
	childPayloads := []map[string]interface{}{}
	if !data.TagTag.IsNull() && !data.TagTag.IsUnknown() {
		tagTagIdentifiers := []TagTagIdentifier{}
		for _, tagTagFvnsAddrInst := range tagTagFvnsAddrInstPlan {
			childMap := NewAciObject()
			if !tagTagFvnsAddrInst.Key.IsNull() && !tagTagFvnsAddrInst.Key.IsUnknown() {
				childMap.Attributes["key"] = tagTagFvnsAddrInst.Key.ValueString()
			}
			if !tagTagFvnsAddrInst.Value.IsNull() && !tagTagFvnsAddrInst.Value.IsUnknown() {
				childMap.Attributes["value"] = tagTagFvnsAddrInst.Value.ValueString()
			}
			childPayloads = append(childPayloads, map[string]interface{}{"tagTag": childMap})
			tagTagIdentifier := TagTagIdentifier{}
			tagTagIdentifier.Key = tagTagFvnsAddrInst.Key
			tagTagIdentifiers = append(tagTagIdentifiers, tagTagIdentifier)
		}
		for _, tagTag := range tagTagFvnsAddrInstState {
			delete := true
			for _, tagTagIdentifier := range tagTagIdentifiers {
				if tagTagIdentifier.Key == tagTag.Key {
					delete = false
					break
				}
			}
			if delete {
				tagTagChildMapForDelete := NewAciObject()
				tagTagChildMapForDelete.Attributes["status"] = "deleted"
				tagTagChildMapForDelete.Attributes["key"] = tagTag.Key.ValueString()
				childPayloads = append(childPayloads, map[string]interface{}{"tagTag": tagTagChildMapForDelete})
			}
		}
	} else {
		data.TagTag = types.SetNull(data.TagTag.ElementType(ctx))
	}

	return childPayloads
}

func getFvnsAddrInstCreateJsonPayload(ctx context.Context, diags *diag.Diagnostics, createType bool, data *FvnsAddrInstResourceModel, fvnsUcastAddrBlkPlan, fvnsUcastAddrBlkState []FvnsUcastAddrBlkFvnsAddrInstResourceModel, tagAnnotationPlan, tagAnnotationState []TagAnnotationFvnsAddrInstResourceModel, tagTagPlan, tagTagState []TagTagFvnsAddrInstResourceModel) *container.Container {
	payloadMap := map[string]interface{}{}
	payloadMap["attributes"] = map[string]string{}

	if createType && !globalAllowExistingOnCreate {
		payloadMap["attributes"].(map[string]string)["status"] = "created"
	}
	childPayloads := []map[string]interface{}{}

	FvnsUcastAddrBlkchildPayloads := getFvnsAddrInstFvnsUcastAddrBlkChildPayloads(ctx, diags, data, fvnsUcastAddrBlkPlan, fvnsUcastAddrBlkState)
	if FvnsUcastAddrBlkchildPayloads == nil {
		return nil
	}
	childPayloads = append(childPayloads, FvnsUcastAddrBlkchildPayloads...)

	TagAnnotationchildPayloads := getFvnsAddrInstTagAnnotationChildPayloads(ctx, diags, data, tagAnnotationPlan, tagAnnotationState)
	if TagAnnotationchildPayloads == nil {
		return nil
	}
	childPayloads = append(childPayloads, TagAnnotationchildPayloads...)

	TagTagchildPayloads := getFvnsAddrInstTagTagChildPayloads(ctx, diags, data, tagTagPlan, tagTagState)
	if TagTagchildPayloads == nil {
		return nil
	}
	childPayloads = append(childPayloads, TagTagchildPayloads...)

	payloadMap["children"] = childPayloads
	if !data.Addr.IsNull() && !data.Addr.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["addr"] = data.Addr.ValueString()
	}
	if !data.AddrType.IsNull() && !data.AddrType.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["addrType"] = data.AddrType.ValueString()
	}
	if !data.Annotation.IsNull() && !data.Annotation.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["annotation"] = data.Annotation.ValueString()
	}
	if !data.Descr.IsNull() && !data.Descr.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["descr"] = data.Descr.ValueString()
	}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["name"] = data.Name.ValueString()
	}
	if !data.NameAlias.IsNull() && !data.NameAlias.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["nameAlias"] = data.NameAlias.ValueString()
	}
	if !data.OwnerKey.IsNull() && !data.OwnerKey.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["ownerKey"] = data.OwnerKey.ValueString()
	}
	if !data.OwnerTag.IsNull() && !data.OwnerTag.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["ownerTag"] = data.OwnerTag.ValueString()
	}
	if !data.SkipGwVal.IsNull() && !data.SkipGwVal.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["skipGwVal"] = data.SkipGwVal.ValueString()
	}
	payload, err := json.Marshal(map[string]interface{}{"fvnsAddrInst": payloadMap})
	if err != nil {
		diags.AddError(
			"Marshalling of json payload failed",
			fmt.Sprintf("Err: %s. Please report this issue to the provider developers.", err),
		)
		return nil
	}

	jsonPayload, err := container.ParseJSON(payload)

	if err != nil {
		diags.AddError(
			"Construction of json payload failed",
			fmt.Sprintf("Err: %s. Please report this issue to the provider developers.", err),
		)
		return nil
	}
	return jsonPayload
}
