// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccResourceNetflowRsMonitorToExporterWithNetflowMonitorPol(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "2.2(1k)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigNetflowRsMonitorToExporterMinDependencyWithNetflowMonitorPolAllowExisting + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test_2", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test_2", "annotation", "orchestrator:terraform"),
				),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "false")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "2.2(1k)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:      testConfigNetflowRsMonitorToExporterMinDependencyWithNetflowMonitorPolAllowExisting + testConfigDataSourceSystem,
				ExpectError: regexp.MustCompile("Object Already Exists"),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "true")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "2.2(1k)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigNetflowRsMonitorToExporterMinDependencyWithNetflowMonitorPolAllowExisting + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test_2", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.allow_test_2", "annotation", "orchestrator:terraform"),
				),
			},
		},
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "both", "2.2(1k)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigNetflowRsMonitorToExporterMinDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotation", "orchestrator:terraform"),
				),
			},
			// Update with all config and verify default APIC values
			{
				Config:             testConfigNetflowRsMonitorToExporterAllDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotation", "annotation"),
				),
			},
			// Update with minimum config and verify config is unchanged
			{
				Config:             testConfigNetflowRsMonitorToExporterMinDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
				),
			},
			// Update with empty strings config or default value
			{
				Config:             testConfigNetflowRsMonitorToExporterResetDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotation", "orchestrator:terraform"),
				),
			},
			// Import testing
			{
				ResourceName:      "aci_relation_to_netflow_exporter.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children
			{
				Config:             testConfigNetflowRsMonitorToExporterChildrenDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "netflow_exporter_policy_name", "test_tn_netflow_exporter_pol_name"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotation", "orchestrator:terraform"),
					composeAggregateTestCheckFuncWithVersion(t, "3.2(1l)-", "inside",
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.0.key", "key_0"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.0.value", "value_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.1.key", "key_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.1.value", "test_value"),
					),
					composeAggregateTestCheckFuncWithVersion(t, "3.2(1l)-", "inside",
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.0.key", "key_0"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.0.value", "value_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.1.key", "key_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.1.value", "test_value"),
					),
				),
			},
			// Refresh State before import testing to ensure that the state is up to date
			{
				RefreshState:       true,
				ExpectNonEmptyPlan: false,
			},
			// Import testing with children
			{
				ResourceName:      "aci_relation_to_netflow_exporter.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children removed from config
			{
				Config:             testConfigNetflowRsMonitorToExporterChildrenRemoveFromConfigDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					composeAggregateTestCheckFuncWithVersion(t, "3.2(1l)-", "inside",
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.0.key", "key_0"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.0.value", "value_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.1.key", "key_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.1.value", "test_value"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.#", "2"),
					),
					composeAggregateTestCheckFuncWithVersion(t, "3.2(1l)-", "inside",
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.0.key", "key_0"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.0.value", "value_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.1.key", "key_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.1.value", "test_value"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.#", "2"),
					),
				),
			},
			// Update with children first child removed
			{
				Config:             testConfigNetflowRsMonitorToExporterChildrenRemoveOneDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					composeAggregateTestCheckFuncWithVersion(t, "3.2(1l)-", "inside",
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.0.key", "key_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.0.value", "test_value"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.#", "1"),
					),
					composeAggregateTestCheckFuncWithVersion(t, "3.2(1l)-", "inside",
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.0.key", "key_1"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.0.value", "test_value"),
						resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.#", "1"),
					),
				),
			},
			// Update with all children removed
			{
				Config:             testConfigNetflowRsMonitorToExporterChildrenRemoveAllDependencyWithNetflowMonitorPol + testConfigDataSourceSystem,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "annotations.#", "0"),
					resource.TestCheckResourceAttr("aci_relation_to_netflow_exporter.test", "tags.#", "0"),
				),
			},
		},
		CheckDestroy: testCheckResourceDestroy,
	})
}

const testConfigNetflowRsMonitorToExporterMinDependencyWithNetflowMonitorPolAllowExisting = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "allow_test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
}
resource "aci_relation_to_netflow_exporter" "allow_test_2" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
  depends_on = [aci_relation_to_netflow_exporter.allow_test]
}
`

const testConfigNetflowRsMonitorToExporterMinDependencyWithNetflowMonitorPol = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
}
`

const testConfigNetflowRsMonitorToExporterAllDependencyWithNetflowMonitorPol = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
  annotation = "annotation"
}
`

const testConfigNetflowRsMonitorToExporterResetDependencyWithNetflowMonitorPol = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
  annotation = "orchestrator:terraform"
}
`
const testConfigNetflowRsMonitorToExporterChildrenDependencyWithNetflowMonitorPol = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
  annotations = provider::aci::compare_versions(data.aci_system.version.version,"inside","3.2(1l)-") ? [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ] : null
  tags = provider::aci::compare_versions(data.aci_system.version.version,"inside","3.2(1l)-") ? [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ] : null
}
`

const testConfigNetflowRsMonitorToExporterChildrenRemoveFromConfigDependencyWithNetflowMonitorPol = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
}
`

const testConfigNetflowRsMonitorToExporterChildrenRemoveOneDependencyWithNetflowMonitorPol = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
  annotations = provider::aci::compare_versions(data.aci_system.version.version,"inside","3.2(1l)-") ? [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ] : null
  tags = provider::aci::compare_versions(data.aci_system.version.version,"inside","3.2(1l)-") ? [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ] : null
}
`

const testConfigNetflowRsMonitorToExporterChildrenRemoveAllDependencyWithNetflowMonitorPol = testConfigNetflowMonitorPolMinDependencyWithFvTenant + `
resource "aci_relation_to_netflow_exporter" "test" {
  parent_dn = aci_netflow_monitor_policy.test.id
  netflow_exporter_policy_name = "test_tn_netflow_exporter_pol_name"
  annotations = provider::aci::compare_versions(data.aci_system.version.version,"inside","3.2(1l)-") ? [] : null
  tags = provider::aci::compare_versions(data.aci_system.version.version,"inside","3.2(1l)-") ? [] : null
}
`
