// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"context"
	"fmt"

	"github.com/ciscoecosystem/aci-go-client/v2/client"
	"github.com/ciscoecosystem/aci-go-client/v2/container"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/list/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ list.ListResource = &FvMacAttrListResource{}
var _ list.ListResourceWithConfigure = &FvMacAttrListResource{}

func NewFvMacAttrListResource() list.ListResource {
	return &FvMacAttrListResource{}
}

type FvMacAttrListResource struct {
	client *client.Client
}

type FvMacAttrListResourceModel struct {
	Filter types.String `tfsdk:"filter"`
}

func (r *FvMacAttrListResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	tflog.Debug(ctx, "Start metadata of list resource: aci_epg_useg_mac_attribute")
	resp.TypeName = req.ProviderTypeName + "_epg_useg_mac_attribute"
	tflog.Debug(ctx, "End metadata of list resource: aci_epg_useg_mac_attribute")
}

func (r *FvMacAttrListResource) ListResourceConfigSchema(ctx context.Context, req list.ListResourceSchemaRequest, resp *list.ListResourceSchemaResponse) {
	tflog.Debug(ctx, "Start schema of list resource: aci_epg_useg_mac_attribute")
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"filter": schema.StringAttribute{
				Description: "The filter that should be applied to the query.",
				Optional:    true,
			},
		},
	}
	tflog.Debug(ctx, "Start schema of list resource: aci_epg_useg_mac_attribute")
}

func (r *FvMacAttrListResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	tflog.Debug(ctx, "Start configure of list resource: aci_epg_useg_mac_attribute")

	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected List Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
	tflog.Debug(ctx, "End configure of list resource: aci_epg_useg_mac_attribute")
}

func (r *FvMacAttrListResource) List(ctx context.Context, req list.ListRequest, stream *list.ListResultsStream) {
	tflog.Debug(ctx, "Start of list resource: aci_epg_useg_mac_attribute")

	var configData FvMacAttrListResourceModel

	var diags diag.Diagnostics
	diags.Append(req.Config.Get(ctx, &configData)...)
	if diags.HasError() {
		return
	}
	path := "api/node/class/fvMacAttr.json?rsp-subtree=full&rsp-subtree-class=tagAnnotation,tagTag"
	if !configData.Filter.IsNull() {
		path = fmt.Sprintf("%s&%s", path, configData.Filter.ValueString())
	}

	requestData := DoRestRequest(ctx, &diags, r.client, path, "GET", nil)

	stream.Results = func(push func(list.ListResult) bool) {
		if requestData.Search("imdata").Search("fvMacAttr").Data() != nil {
			imdataAmount, _ := requestData.Search("imdata").ArrayCount()
			for i := range imdataAmount {
				imdata, err := requestData.Search("imdata").ArrayElement(i)
				if err != nil {
					return
				}

				imdataCont := container.New()
				imdataCont.Set([]interface{}{imdata.Data()}, "imdata")
				fvMacAttr := getEmptyFvMacAttrResourceModel()
				setFvMacAttrAttributes(ctx, &diags, fvMacAttr, imdataCont)
				result := req.NewListResult(ctx)
				diags.Append(result.Identity.Set(ctx, IdentityModel{
					Id: fvMacAttr.Id,
				})...)

				if diags.HasError() {
					return
				}

				diags.Append(result.Resource.Set(ctx, fvMacAttr)...)
				if diags.HasError() {
					return
				}

				if !push(result) {
					return
				}

			}
		}
	}

	tflog.Debug(ctx, "End of list resource: aci_epg_useg_mac_attribute")
}
